import { and, eq } from "drizzle-orm";
import { notFound, redirect } from "next/navigation";
import { ExternalLink, FileArchive, Globe2, HardDrive } from "lucide-react";
import { RefreshDeployment } from "@/components/hosting/refresh-deployment";
import { Button } from "@/components/ui/button";
import { db } from "@/lib/db";
import { getViewer } from "@/lib/db/access";
import { hostedSites } from "@/lib/db/schema";
import { isLocale } from "@/lib/i18n";
const copy={ar:{status:"الحالة",framework:"نوع المشروع",files:"عدد الملفات",size:"الحجم",visit:"زيارة الموقع",refresh:"تحديث الحالة",back:"كل المواقع"},en:{status:"Status",framework:"Framework",files:"Files",size:"Size",visit:"Visit site",refresh:"Refresh status",back:"All sites"},nl:{status:"Status",framework:"Type",files:"Bestanden",size:"Grootte",visit:"Site bezoeken",refresh:"Status vernieuwen",back:"Alle sites"},de:{status:"Status",framework:"Typ",files:"Dateien",size:"Größe",visit:"Website öffnen",refresh:"Status aktualisieren",back:"Alle Websites"},tr:{status:"Durum",framework:"Tür",files:"Dosyalar",size:"Boyut",visit:"Siteyi ziyaret et",refresh:"Durumu yenile",back:"Tüm siteler"},fr:{status:"État",framework:"Type",files:"Fichiers",size:"Taille",visit:"Visiter",refresh:"Actualiser",back:"Tous les sites"},es:{status:"Estado",framework:"Tipo",files:"Archivos",size:"Tamaño",visit:"Visitar",refresh:"Actualizar",back:"Todos los sitios"}} as const;
export default async function SitePage({params}:{params:Promise<{locale:string;id:string}>}){const{locale:raw,id}=await params;if(!isLocale(raw))notFound();const viewer=await getViewer();if(!viewer)redirect(`/${raw}/login?next=/${raw}/hosting/${id}`);const[site]=await db.select().from(hostedSites).where(and(eq(hostedSites.id,id),eq(hostedSites.userId,viewer.id))).limit(1);if(!site)notFound();const c=copy[raw];return <div className="bg-base"><div className="container-x py-16 sm:py-24"><Button asChild variant="ghostNeon"><a href={`/${raw}/hosting`}>← {c.back}</a></Button><div className="mt-8 rounded-[2rem] border border-black bg-white p-7 sm:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-widest text-ink-low">{site.projectName}</p><h1 className="mt-3 text-4xl font-black text-black sm:text-6xl">{site.name}</h1></div><span className="rounded-full bg-black px-4 py-2 text-sm font-bold text-white">{site.status}</span></div><div className="mt-10 grid gap-3 sm:grid-cols-3"><article className="rounded-2xl bg-base p-5"><Globe2/><p className="mt-5 text-xs text-ink-low">{c.framework}</p><strong>{site.framework}</strong></article><article className="rounded-2xl bg-base p-5"><FileArchive/><p className="mt-5 text-xs text-ink-low">{c.files}</p><strong>{site.fileCount}</strong></article><article className="rounded-2xl bg-base p-5"><HardDrive/><p className="mt-5 text-xs text-ink-low">{c.size}</p><strong>{(site.totalBytes/1024/1024).toFixed(2)} MB</strong></article></div>{site.errorMessage?<p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{site.errorMessage}</p>:null}<div className="mt-8 flex flex-wrap gap-3"><RefreshDeployment id={site.id} label={c.refresh}/>{site.url?<Button asChild variant="neon"><a href={`https://${site.url}`} target="_blank" rel="noreferrer">{c.visit}<ExternalLink className="size-4"/></a></Button>:null}</div></div></div></div>}
