import "server-only";
import {and,eq,desc,inArray} from "drizzle-orm";
import {db,isDatabaseConfigured} from "./index";
import {marketplaceListings as listings,marketplaceOffers,marketplaceOrders,payments,projects,users} from "./schema";
import {listingActive,type ListingKind,jobTiers,type JobTier} from "../marketplace";
export const listingColumns={id:listings.id,userId:listings.userId,kind:listings.kind,title:listings.title,description:listings.description,category:listings.category,price:listings.price,tier:listings.tier,status:listings.status,company:listings.company,location:listings.location,platformProduct:listings.platformProduct,assetName:listings.assetName,moderatedAt:listings.moderatedAt,createdAt:listings.createdAt};
export async function jobPaidAt(id:string){const [row]=await db.select({paidAt:payments.paidAt}).from(marketplaceOrders).innerJoin(payments,eq(payments.projectId,marketplaceOrders.projectId)).where(and(eq(marketplaceOrders.listingId,id),eq(marketplaceOrders.kind,"job"),eq(payments.status,"paid"),eq(payments.environment,"live"))).orderBy(desc(payments.paidAt)).limit(1);return row?.paidAt??null;}
export async function publicListings(kind:ListingKind){if(!isDatabaseConfigured)return[];const rows=await db.select(listingColumns).from(listings).where(and(eq(listings.kind,kind),eq(listings.status,"approved"))).orderBy(desc(listings.createdAt)).limit(100);
 const paidRows=kind==="job"&&rows.length?await db.select({listingId:marketplaceOrders.listingId,paidAt:payments.paidAt}).from(marketplaceOrders).innerJoin(payments,eq(payments.projectId,marketplaceOrders.projectId)).where(and(inArray(marketplaceOrders.listingId,rows.map(row=>row.id)),eq(payments.status,"paid"),eq(payments.environment,"live"))).orderBy(desc(payments.paidAt)):[];
 const paid=new Map<string,Date>();for(const row of paidRows)if(row.paidAt&&!paid.has(row.listingId))paid.set(row.listingId,row.paidAt);
 return rows.filter(row=>listingActive(row.status,row.kind,row.tier,row.moderatedAt,paid.get(row.id)??null)).sort((a,b)=>(jobTiers[b.tier as JobTier]?.rank??0)-(jobTiers[a.tier as JobTier]?.rank??0));}
export async function visibleListing(id:string,userId?:string){if(!isDatabaseConfigured)return null;const [row]=await db.select(listingColumns).from(listings).where(eq(listings.id,id)).limit(1);if(!row)return null;
 if(row.userId===userId)return row;
 return listingActive(row.status,row.kind,row.tier,row.moderatedAt,row.kind==="job"&&row.tier!=="basic"?await jobPaidAt(id):null)?row:null;}
export async function ownListings(userId:string){return db.select(listingColumns).from(listings).where(eq(listings.userId,userId)).orderBy(desc(listings.createdAt)).limit(100);}
export async function listingOffers(listingId:string,userId:string){const [listing]=await db.select({userId:listings.userId}).from(listings).where(eq(listings.id,listingId));if(!listing)return[];
 return db.select({id:marketplaceOffers.id,message:marketplaceOffers.message,amount:marketplaceOffers.amount,status:marketplaceOffers.status,name:users.name,email:users.email}).from(marketplaceOffers).innerJoin(users,eq(users.id,marketplaceOffers.userId)).where(and(eq(marketplaceOffers.listingId,listingId),...(listing.userId===userId?[]:[eq(marketplaceOffers.userId,userId)]))).orderBy(desc(marketplaceOffers.createdAt)).limit(100);}
export async function purchases(userId:string){return db.select({id:projects.id,title:marketplaceOrders.snapshot,kind:marketplaceOrders.kind,status:payments.status,paidAt:payments.paidAt,listingStatus:listings.status,listingId:marketplaceOrders.listingId}).from(marketplaceOrders).innerJoin(projects,eq(projects.id,marketplaceOrders.projectId)).innerJoin(listings,eq(listings.id,marketplaceOrders.listingId)).leftJoin(payments,and(eq(payments.projectId,projects.id),eq(payments.billingStage,"legacy"),eq(payments.environment,"live"))).where(eq(projects.clientId,userId)).orderBy(desc(marketplaceOrders.createdAt)).limit(100);}
export async function commerceProjectIds(ids:string[]){if(!ids.length)return[];return db.select({id:marketplaceOrders.projectId}).from(marketplaceOrders).where(inArray(marketplaceOrders.projectId,ids));}
