"use client";
import { useState } from "react";
import Link from "next/link";
import { FileSearch, CircleCheck, CircleAlert, CircleHelp, Printer, Download } from "lucide-react";
import { useI18n } from "@/components/providers";
import { platformCopy } from "@/lib/i18n/platform-tools";
import type { AuditReport, AuditCategory } from "@/lib/audits/types";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
const categories: AuditCategory[] = ["security", "seo", "accessibility", "performance", "links", "source"];
export function AuditReportView({ id, report, canExport, previous, compareLinks }: { id: string; report: AuditReport; canExport: boolean; previous: AuditReport | null; compareLinks: { id: string; createdAt: string }[] }) {
  const { locale, t } = useI18n(); const c = platformCopy(locale); const [visible, setVisible] = useState(40);
  const totals = { pass: report.checks.filter(row => row.status === "pass").length, warning: report.checks.filter(row => row.status === "warning").length, not_tested: report.checks.filter(row => row.status === "not_tested").length };
  function print() { setVisible(report.checks.length); requestAnimationFrame(() => requestAnimationFrame(() => window.print())); }
  return <div className="space-y-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-3 text-sm text-white/60">Blue Sass</p><h1 className="text-3xl font-bold sm:text-5xl">{c.report}</h1><p className="mt-4 break-all text-lg text-white/75" dir="auto">{report.target}</p><p className="mt-2 text-xs text-white/55" dir="ltr">{report.generatedAt.slice(0, 19).replace("T", " ")} UTC</p></div><div className="flex flex-wrap gap-3" data-no-print><Button type="button" variant="neon" onClick={print}><Printer className="size-4"/>{c.print}</Button>{canExport && <Button asChild variant="outline"><Link href={`/api/audits/${id}/export`}><Download className="size-4"/>{c.exportJson}</Link></Button>}<Button asChild variant="outline"><Link href={`/${locale}/audit`}>{c.history}</Link></Button></div></div>
    <div className="grid gap-4 sm:grid-cols-3">{[{ label: c.passed, value: totals.pass, icon: CircleCheck }, { label: c.warning, value: totals.warning, icon: CircleAlert }, { label: c.notTested, value: totals.not_tested, icon: CircleHelp }].map(item => <Card key={item.label} className="tool-card"><CardContent className="flex items-center justify-between gap-4 pt-6"><div><p className="text-sm text-white/60">{item.label}</p><p className="mt-3 text-3xl font-semibold">{item.value}</p></div><item.icon className="size-6 text-white/50"/></CardContent></Card>)}</div>
    <Card className="tool-card"><CardContent className="pt-6"><p className="text-sm leading-8 text-white/70">{c.limits}</p><div className="mt-4 flex flex-wrap gap-5 text-xs text-white/60"><span>{c.selected}: {report.scannedFiles}</span><span>{c.ignored}: {report.skippedFiles}</span><span>{(report.bytes / 1_000_000).toFixed(2)} MB</span></div></CardContent></Card>
    {compareLinks.length > 0 && <Card className="tool-card" data-no-print><CardHeader><CardTitle className="text-white">{c.compare}</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3">{compareLinks.map(row => <Button asChild key={row.id} variant="outline" size="sm"><Link href={`/${locale}/audit/${id}?compare=${row.id}`}>{row.createdAt.slice(0, 10)} · {row.id.slice(0, 6)}</Link></Button>)}</CardContent></Card>}
    {previous && <Card className="tool-card"><CardHeader><CardTitle className="text-white">{c.compare}</CardTitle></CardHeader><CardContent><p className="text-sm leading-7">{c.previous}: {previous.checks.filter(row => row.status === "warning").length} · {c.warning}: {totals.warning}</p><p className="mt-3 text-xs text-white/60">{previous.generatedAt.slice(0, 10)} → {report.generatedAt.slice(0, 10)}</p></CardContent></Card>}
    <div className="grid items-start gap-5 lg:grid-cols-2">{categories.map(category => {
      const checks = report.checks.filter(row => row.category === category); if (!checks.length) return null;
      return <Card key={category} className="tool-card"><CardHeader><CardTitle className="flex items-center gap-3 text-white"><FileSearch className="size-5"/>{c.categories[category]}</CardTitle></CardHeader><CardContent><ul className="space-y-4">{checks.slice(0, visible).map((row, index) => <li key={`${row.code}-${row.file ?? ""}-${index}`} className="rounded-xl border border-white/15 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><strong className="text-sm leading-7">{c.rules[row.code as keyof typeof c.rules] ?? row.code}</strong><span className="rounded-full border border-white/20 px-2 py-1 text-[11px]">{row.status === "pass" ? c.passed : row.status === "warning" ? c.warning : c.notTested}</span></div>{row.file && <p className="mt-2 break-all font-mono text-xs text-white/60" dir="ltr">{row.file}</p>}{row.count !== undefined && <p className="mt-2 text-sm tabular-nums">{row.count}</p>}{row.metric !== undefined && <p className="mt-2 text-sm tabular-nums">{row.metric.toLocaleString("en-US")}</p>}{row.status === "warning" && <p className="mt-3 text-xs leading-7 text-white/65">{c.recommendations[row.code as keyof typeof c.recommendations] ?? c.limits}</p>}</li>)}</ul>{checks.length > visible && <Button type="button" variant="outline" className="mt-5" onClick={() => setVisible(value => value + 40)} data-no-print>{c.more}</Button>}</CardContent></Card>;
    })}</div>
    <div className="flex flex-wrap gap-3" data-no-print><Button asChild variant="neon"><Link href={`/${locale}/quote`}>{c.requestImprovement}</Link></Button><Button asChild variant="outline"><Link href={`/${locale}/audit`}>{t.common.back}</Link></Button></div><p className="text-xs leading-8 text-white/55">{c.privacy}</p>
  </div>;
}
