"use client";

import { useState } from "react";
import { ChevronDown, Plus } from "lucide-react";
import { useI18n } from "@/components/providers";
import { Button } from "@/components/ui/button";
import { Reveal, motion } from "@/components/ui/motion";

const copy = {
  ar: { title: "أسئلة تساعدك على اتخاذ القرار", intro: "مختصر وواضح قبل أن تبدأ.", more: "عرض جميع الأسئلة", less: "عرض أقل", qs: ["كيف أبدأ مشروعًا مع بلو ساس؟", "متى يبدأ تنفيذ مشروعي؟", "كم يستغرق التصميم والتطوير؟", "كيف يتم الدفع؟", "هل الأسعار نهائية؟", "هل تدعمون العربية وRTL؟", "من يملك الموقع والملفات؟", "هل يمكن تعديل الطلب أو إلغاؤه؟"], ans: ["اختر الخدمة أو القالب، أكمل تفاصيل مشروعك واحفظه، ثم انتقل إلى الدفع الآمن.", "لا ينتقل المشروع إلى التخطيط إلا بعد تأكيد PayPal أن الدفعة مكتملة.", "تظهر مدة تقديرية لكل نوع مشروع، ثم نثبت الجدول بعد مراجعة النطاق.", "يمكن الدفع عبر PayPal أو البطاقات المدعومة داخل PayPal Checkout، ولا نخزن بيانات بطاقتك.", "هي أسعار بداية واضحة. أي تكامل أو نطاق إضافي يظهر في العرض قبل الدفع.", "نعم، نبني الواجهة العربية واتجاه RTL وتعدد اللغات من البداية.", "بعد سداد المشروع كاملًا وتسليمه، تنتقل لك الملفات والحقوق الموضحة في الاتفاق.", "يمكن التعديل أو الإلغاء قبل انتقال المشروع إلى التصميم؛ بعدها تطبق شروط التنفيذ المتفق عليها."] },
  en: { title: "Questions that help you decide", intro: "Clear answers before you start.", more: "View all questions", less: "Show fewer", qs: ["How do I start a project?", "When does work begin?", "How long does delivery take?", "How do payments work?", "Are prices final?", "Do you support Arabic and RTL?", "Who owns the website and files?", "Can I change or cancel an order?"], ans: ["Choose a service or template, complete and save your brief, then continue to secure checkout.", "A project does not enter planning until PayPal confirms the payment as completed.", "Each project type has an estimate; the schedule is confirmed after scope review.", "Pay securely with PayPal or supported cards through PayPal Checkout. We never store card details.", "They are transparent starting prices. Extra scope is shown in the proposal before payment.", "Yes. Arabic, RTL and multilingual experiences are supported from day one.", "After final payment and delivery, the agreed files and rights are transferred to you.", "Changes or cancellation are possible before design begins; agreed delivery terms apply afterwards."] },
  nl: { title: "Vragen die helpen beslissen", intro: "Heldere antwoorden voordat u start.", more: "Alle vragen bekijken", less: "Minder tonen", qs: ["Hoe start ik een project?", "Wanneer begint het werk?", "Hoe lang duurt de oplevering?", "Hoe werkt betalen?", "Zijn prijzen definitief?", "Ondersteunen jullie Arabisch en RTL?", "Wie bezit de website en bestanden?", "Kan ik wijzigen of annuleren?"], ans: ["Kies een dienst of template, vul de briefing in, sla die op en ga veilig betalen.", "Een project gaat pas naar planning nadat PayPal de betaling als voltooid bevestigt.", "Elk projecttype heeft een indicatie; na scopecontrole bevestigen we de planning.", "Betaal via PayPal of ondersteunde kaarten. Wij bewaren nooit kaartgegevens.", "Dit zijn transparante vanafprijzen; extra scope staat vóór betaling in het voorstel.", "Ja, Arabisch, RTL en meertaligheid worden vanaf het begin ondersteund.", "Na volledige betaling en oplevering ontvangt u de afgesproken bestanden en rechten.", "Wijzigen of annuleren kan vóór de ontwerpfase; daarna gelden de afgesproken voorwaarden."] },
  de: { title: "Fragen für eine klare Entscheidung", intro: "Klare Antworten vor dem Start.", more: "Alle Fragen anzeigen", less: "Weniger anzeigen", qs: ["Wie starte ich ein Projekt?", "Wann beginnt die Arbeit?", "Wie lange dauert die Lieferung?", "Wie funktioniert die Zahlung?", "Sind die Preise endgültig?", "Unterstützt ihr Arabisch und RTL?", "Wem gehören Website und Dateien?", "Kann ich ändern oder stornieren?"], ans: ["Wählen Sie Dienst oder Vorlage, speichern Sie Ihr Briefing und gehen Sie zur sicheren Zahlung.", "Die Planung beginnt erst, wenn PayPal die Zahlung als abgeschlossen bestätigt.", "Für jeden Projekttyp gibt es eine Schätzung; danach bestätigen wir den Zeitplan.", "Zahlen Sie sicher über PayPal oder unterstützte Karten. Wir speichern keine Kartendaten.", "Es sind transparente Startpreise; Zusatzumfang wird vor Zahlung ausgewiesen.", "Ja, Arabisch, RTL und Mehrsprachigkeit werden von Anfang an unterstützt.", "Nach vollständiger Zahlung erhalten Sie die vereinbarten Dateien und Rechte.", "Änderungen oder Storno sind vor Designbeginn möglich; danach gelten die Bedingungen."] },
  tr: { title: "Karar vermenizi kolaylaştıran sorular", intro: "Başlamadan önce net cevaplar.", more: "Tüm soruları göster", less: "Daha az göster", qs: ["Projeye nasıl başlarım?", "Çalışma ne zaman başlar?", "Teslimat ne kadar sürer?", "Ödeme nasıl yapılır?", "Fiyatlar kesin mi?", "Arapça ve RTL desteği var mı?", "Site ve dosyaların sahibi kim?", "Siparişi değiştirebilir veya iptal edebilir miyim?"], ans: ["Hizmet veya şablon seçin, brifingi kaydedin ve güvenli ödemeye geçin.", "PayPal ödemeyi tamamlandı olarak doğrulamadan proje planlamaya geçmez.", "Her proje için süre tahmini vardır; kapsam incelemesinden sonra takvim netleşir.", "PayPal veya desteklenen kartlarla ödeyin. Kart bilgilerini saklamayız.", "Bunlar şeffaf başlangıç fiyatlarıdır; ek kapsam ödeme öncesinde gösterilir.", "Evet, Arapça, RTL ve çok dil desteği başlangıçtan itibaren sunulur.", "Tam ödeme ve teslimden sonra kararlaştırılan dosya ve haklar size geçer.", "Tasarım başlamadan değişiklik veya iptal mümkündür; sonrasında koşullar uygulanır."] },
  fr: { title: "Les questions utiles avant de décider", intro: "Des réponses claires avant de commencer.", more: "Voir toutes les questions", less: "Afficher moins", qs: ["Comment démarrer un projet ?", "Quand commence le travail ?", "Quel est le délai ?", "Comment fonctionne le paiement ?", "Les prix sont-ils définitifs ?", "Prenez-vous en charge l’arabe et le RTL ?", "Qui possède le site et les fichiers ?", "Puis-je modifier ou annuler ?"], ans: ["Choisissez un service ou modèle, enregistrez votre brief puis passez au paiement sécurisé.", "Le projet ne passe en planification qu’après confirmation du paiement par PayPal.", "Chaque type affiche une estimation, confirmée après analyse du périmètre.", "Payez via PayPal ou une carte compatible. Nous ne stockons aucune donnée bancaire.", "Ce sont des prix de départ transparents; tout ajout est présenté avant paiement.", "Oui, l’arabe, le RTL et le multilingue sont pris en charge dès le départ.", "Après paiement complet et livraison, les fichiers et droits convenus vous reviennent.", "Modification ou annulation avant le design; ensuite les conditions convenues s’appliquent."] },
  es: { title: "Preguntas para decidir con claridad", intro: "Respuestas claras antes de empezar.", more: "Ver todas las preguntas", less: "Mostrar menos", qs: ["¿Cómo empiezo un proyecto?", "¿Cuándo empieza el trabajo?", "¿Cuánto tarda la entrega?", "¿Cómo funciona el pago?", "¿Los precios son definitivos?", "¿Admiten árabe y RTL?", "¿Quién posee el sitio y los archivos?", "¿Puedo cambiar o cancelar?"], ans: ["Elija un servicio o plantilla, guarde el briefing y continúe al pago seguro.", "El proyecto no pasa a planificación hasta que PayPal confirme el pago completado.", "Cada tipo tiene una estimación; confirmamos el calendario tras revisar el alcance.", "Pague con PayPal o tarjetas compatibles. Nunca almacenamos datos de la tarjeta.", "Son precios iniciales transparentes; cualquier extra se muestra antes del pago.", "Sí, árabe, RTL y multilingüe están disponibles desde el inicio.", "Tras el pago completo y la entrega recibe los archivos y derechos acordados.", "Puede cambiar o cancelar antes del diseño; después se aplican las condiciones acordadas."] },
} as const;

export function HomeFaq() {
  const { locale } = useI18n();
  const c = copy[locale];
  const [open, setOpen] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const questions = expanded ? c.qs : c.qs.slice(0, 4);
  return <section className="section-y bg-base"><div className="container-x grid gap-10 lg:grid-cols-[.65fr_1fr]">
    <Reveal><span className="grid size-12 place-items-center rounded-full bg-black text-white"><Plus className="size-5"/></span><h2 className="mt-5 text-4xl font-bold text-black sm:text-6xl">{c.title}</h2><p className="mt-4 max-w-sm leading-8 text-ink-low">{c.intro}</p></Reveal>
    <div className="min-w-0 space-y-3">{questions.map((q,i)=><Reveal key={q} delay={i*.04}><article className={`overflow-hidden rounded-2xl border border-black transition-colors ${open===i?"bg-neon-cyan":"bg-white"}`}><Button variant="unstyled" size="auto" type="button" aria-expanded={open===i} aria-controls={`faq-answer-${i}`} onClick={()=>setOpen(open===i?-1:i)} className="flex h-auto w-full items-center justify-between gap-4 p-5 text-start text-lg font-bold text-black hover:bg-black/[.03]"><span className="min-w-0 whitespace-normal leading-7">{q}</span><ChevronDown className={`size-5 shrink-0 transition-transform ${open===i?"rotate-180":""}`}/></Button>{open===i&&<motion.div id={`faq-answer-${i}`} initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} className="px-5 pb-5"><p className="w-full border-t border-black/15 pt-4 text-start leading-8 text-black/65 [overflow-wrap:anywhere]">{c.ans[i]}</p></motion.div>}</article></Reveal>)}<Button variant="unstyled" size="auto" onClick={()=>{setExpanded(!expanded); setOpen(0);}} className="mt-4 rounded-full border border-black bg-black px-6 py-3 font-bold text-white transition-transform hover:-translate-y-1">{expanded?c.less:c.more}</Button></div>
  </div></section>;
}
