"use client";

import { useState } from "react";
import { ChevronDown, Quote, Star } from "lucide-react";
import { useI18n } from "@/components/providers";
import { Reveal, motion } from "@/components/ui/motion";

const copy = {
  ar: { reviews: "ماذا يقول عملاؤنا", reviewSub: "تجارب حقيقية مع فريق بلو ساس", faq: "الأسئلة الشائعة", faqSub: "إجابات واضحة قبل أن تبدأ مشروعك", names: ["أحمد — هولندا", "سارة — ألمانيا", "محمود — بلجيكا"], quotes: ["حوّلوا الفكرة إلى موقع واضح وسريع، وكانت المتابعة ممتازة في كل مرحلة.", "أحببت التنظيم وسهولة التواصل. التصميم النهائي أفضل بكثير مما تخيلت.", "فريق محترف ومرن، والتسليم كان واضحًا مع دعم حقيقي بعد الإطلاق."], qs: ["كيف نبدأ مشروعًا مع بلو ساس؟", "كم يستغرق تصميم وتطوير الموقع؟", "هل تدعمون اللغة العربية وRTL؟", "هل تقدمون دعمًا بعد الإطلاق؟"], ans: ["ابدأ من نموذج المشروع أو تواصل معنا. نراجع الفكرة ونحدد النطاق ثم نرسل خطة واضحة.", "تختلف المدة حسب النطاق، وغالبًا تبدأ المشاريع المتوسطة من عدة أسابيع مع جدول تسليم واضح.", "نعم، نبني التجربة العربية من الأساس وندعم اللغات المتعددة واتجاه RTL بالكامل.", "نعم، نوفر المتابعة والصيانة والتحسينات بعد التسليم وفق احتياج المشروع."] },
  en: { reviews: "What clients say", reviewSub: "Real experiences with Blue Sass", faq: "Frequently asked questions", faqSub: "Clear answers before you start", names: ["Ahmed — Netherlands", "Sarah — Germany", "Mahmoud — Belgium"], quotes: ["They turned the idea into a clear, fast website and communication was excellent.", "The process was organised and the final design exceeded my expectations.", "A professional, flexible team with genuine support after launch."], qs: ["How do we start?", "How long does a project take?", "Do you support Arabic and RTL?", "Is support available after launch?"], ans: ["Use the project form or contact us. We review the idea and send a clear plan.", "Timing depends on scope; medium projects usually take several weeks with a clear schedule.", "Yes. Arabic, multilingual content and RTL are supported from the start.", "Yes. We offer ongoing support, maintenance and improvements after delivery."] },
  nl: { reviews: "Wat klanten zeggen", reviewSub: "Ervaringen met Blue Sass", faq: "Veelgestelde vragen", faqSub: "Duidelijke antwoorden voordat u start", names: ["Ahmed — Nederland", "Sarah — Duitsland", "Mahmoud — België"], quotes: ["Een helder en snel resultaat met uitstekende communicatie.", "Een georganiseerd proces en een ontwerp boven verwachting.", "Professioneel, flexibel en echte ondersteuning na livegang."], qs: ["Hoe starten we?", "Hoe lang duurt een project?", "Ondersteunen jullie Arabisch en RTL?", "Is er nazorg?"], ans: ["Gebruik het projectformulier; daarna ontvangt u een helder plan.", "De planning hangt af van de omvang en wordt vooraf duidelijk afgesproken.", "Ja, meertaligheid en RTL worden volledig ondersteund.", "Ja, wij bieden onderhoud en doorlopende ondersteuning."] },
  de: { reviews: "Was Kunden sagen", reviewSub: "Erfahrungen mit Blue Sass", faq: "Häufige Fragen", faqSub: "Klare Antworten vor dem Start", names: ["Ahmed — Niederlande", "Sarah — Deutschland", "Mahmoud — Belgien"], quotes: ["Klares, schnelles Ergebnis und hervorragende Kommunikation.", "Ein organisierter Prozess und ein Design über unseren Erwartungen.", "Professionell, flexibel und echter Support nach dem Launch."], qs: ["Wie starten wir?", "Wie lange dauert ein Projekt?", "Unterstützt ihr Arabisch und RTL?", "Gibt es Support danach?"], ans: ["Nutzen Sie das Projektformular; danach erhalten Sie einen klaren Plan.", "Die Dauer hängt vom Umfang ab und wird vorher transparent geplant.", "Ja, Mehrsprachigkeit und RTL werden vollständig unterstützt.", "Ja, wir bieten Wartung und laufenden Support."] },
  tr: { reviews: "Müşteriler ne diyor", reviewSub: "Blue Sass deneyimleri", faq: "Sık sorulan sorular", faqSub: "Başlamadan önce net cevaplar", names: ["Ahmed — Hollanda", "Sarah — Almanya", "Mahmoud — Belçika"], quotes: ["Net, hızlı bir sonuç ve mükemmel iletişim.", "Düzenli süreç ve beklentimizin üzerinde tasarım.", "Profesyonel, esnek ve lansman sonrası gerçek destek."], qs: ["Nasıl başlarız?", "Proje ne kadar sürer?", "Arapça ve RTL var mı?", "Lansman sonrası destek var mı?"], ans: ["Proje formunu kullanın; ardından net bir plan sunarız.", "Süre kapsama bağlıdır ve baştan şeffaf biçimde planlanır.", "Evet, çok dil ve RTL tam desteklenir.", "Evet, bakım ve sürekli destek sunuyoruz."] },
  fr: { reviews: "Ce que disent nos clients", reviewSub: "Expériences avec Blue Sass", faq: "Questions fréquentes", faqSub: "Des réponses claires avant de commencer", names: ["Ahmed — Pays-Bas", "Sarah — Allemagne", "Mahmoud — Belgique"], quotes: ["Un résultat clair et rapide avec une excellente communication.", "Un processus organisé et un design au-delà de nos attentes.", "Une équipe professionnelle, flexible et présente après le lancement."], qs: ["Comment commencer ?", "Combien de temps faut-il ?", "L’arabe et le RTL sont-ils pris en charge ?", "Y a-t-il un suivi ?"], ans: ["Utilisez le formulaire projet et nous vous enverrons un plan clair.", "Le délai dépend du périmètre et est défini de façon transparente.", "Oui, le multilingue et le RTL sont pleinement pris en charge.", "Oui, maintenance et support continu sont disponibles."] },
  es: { reviews: "Lo que dicen los clientes", reviewSub: "Experiencias con Blue Sass", faq: "Preguntas frecuentes", faqSub: "Respuestas claras antes de empezar", names: ["Ahmed — Países Bajos", "Sarah — Alemania", "Mahmoud — Bélgica"], quotes: ["Un resultado claro y rápido con excelente comunicación.", "Un proceso organizado y un diseño por encima de lo esperado.", "Un equipo profesional, flexible y con soporte tras el lanzamiento."], qs: ["¿Cómo empezamos?", "¿Cuánto tarda un proyecto?", "¿Admiten árabe y RTL?", "¿Hay soporte posterior?"], ans: ["Use el formulario del proyecto y recibirá un plan claro.", "El plazo depende del alcance y se acuerda con transparencia.", "Sí, se admite multilingüe y RTL por completo.", "Sí, ofrecemos mantenimiento y soporte continuo."] },
} as const;

export function TestimonialsAndFaq() {
  const { locale } = useI18n();
  const c = copy[locale];
  const [open, setOpen] = useState(0);
  return <>
    <section className="section-y bg-white"><div className="container-x"><Reveal className="text-center"><span className="text-sm font-bold text-neon-magenta">✦ Blue Sass</span><h2 className="mt-3 text-4xl font-bold text-black sm:text-6xl">{c.reviews}</h2><p className="mt-4 text-ink-low">{c.reviewSub}</p></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{c.quotes.map((quote, i) => <Reveal key={quote} delay={i*.07}><motion.blockquote whileHover={{ y: -7 }} className={`h-full rounded-2xl border border-black p-7 ${i===1 ? "bg-neon-cyan" : "bg-base"}`}><Quote className="size-9 text-neon-blue"/><div className="mt-6 flex gap-1">{[1,2,3,4,5].map(n=><Star key={n} className="size-4 fill-neon-magenta text-neon-magenta"/>)}</div><p className="mt-5 text-base leading-8 text-black">{quote}</p><footer className="mt-7 border-t border-black/15 pt-4 text-sm font-bold text-black">{c.names[i]}</footer></motion.blockquote></Reveal>)}</div></div></section>
    <section className="section-y bg-base"><div className="container-x grid gap-10 lg:grid-cols-[.7fr_1fr]"><Reveal><span className="text-sm font-bold text-neon-magenta">✦ FAQ</span><h2 className="mt-3 text-4xl font-bold text-black sm:text-6xl">{c.faq}</h2><p className="mt-4 max-w-md leading-8 text-ink-low">{c.faqSub}</p></Reveal><div className="space-y-3">{c.qs.map((q,i)=><Reveal key={q} delay={i*.04}><button type="button" onClick={()=>setOpen(open===i?-1:i)} className={`w-full rounded-2xl border border-black p-5 text-start transition ${open===i?"bg-neon-cyan":"bg-white"}`}><span className="flex items-center justify-between gap-4 text-lg font-bold text-black">{q}<ChevronDown className={`size-5 transition-transform ${open===i?"rotate-180":""}`}/></span>{open===i&&<motion.p initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} className="mt-4 border-t border-black/15 pt-4 leading-8 text-black/65">{c.ans[i]}</motion.p>}</button></Reveal>)}</div></div></section>
  </>;
}
