"use client";

import { useActionState } from "react";
import { MessageSquareQuote, Send, Star } from "lucide-react";
import { submitReviewAction, type ReviewState } from "@/app/actions/reviews";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { Locale } from "@/lib/i18n";
import type { Review } from "@/lib/db/schema";

const copy = {
  ar: { eyebrow: "آراء حقيقية · نشر بعد المراجعة", title: "شارك تجربتك مع Blue Sass", intro: "اقرأ آراء العملاء أو أرسل تجربتك. لا ننشر أي رأي قبل فحصه، ولا نعرض بريدك الإلكتروني.", form: "أرسل رأيك", rating: "التقييم", body: "اكتب تجربتك بالتفصيل", placeholder: "ما الخدمة التي حصلت عليها؟ وما أكثر شيء أفاد مشروعك؟", submit: "إرسال للمراجعة", empty: "لم تُنشر آراء بعد. يمكنك أن تكون أول من يشارك تجربته.", login: "سجّل الدخول لإرسال رأيك" },
  en: { eyebrow: "Real feedback · Moderated before publishing", title: "Share your Blue Sass experience", intro: "Read customer feedback or submit your experience. We never publish a review before moderation or reveal your email.", form: "Submit a review", rating: "Rating", body: "Describe your experience", placeholder: "Which service did you use and what helped your project most?", submit: "Send for review", empty: "No reviews have been published yet. You can be the first to share your experience.", login: "Sign in to submit a review" },
  nl: { eyebrow: "Echte feedback · Eerst beoordeeld", title: "Deel uw Blue Sass-ervaring", intro: "Lees ervaringen of deel die van u. E-mailadressen worden nooit getoond.", form: "Review plaatsen", rating: "Beoordeling", body: "Uw ervaring", placeholder: "Welke dienst gebruikte u en wat hielp het meest?", submit: "Ter beoordeling verzenden", empty: "Nog geen gepubliceerde reviews.", login: "Log in om een review te plaatsen" },
  de: { eyebrow: "Echtes Feedback · Vor Veröffentlichung geprüft", title: "Teilen Sie Ihre Blue Sass-Erfahrung", intro: "Lesen oder teilen Sie Kundenerfahrungen. E-Mail-Adressen werden nicht veröffentlicht.", form: "Bewertung senden", rating: "Bewertung", body: "Ihre Erfahrung", placeholder: "Welche Leistung haben Sie genutzt?", submit: "Zur Prüfung senden", empty: "Noch keine veröffentlichten Bewertungen.", login: "Anmelden, um zu bewerten" },
  tr: { eyebrow: "Gerçek görüşler · Yayından önce incelenir", title: "Blue Sass deneyiminizi paylaşın", intro: "Müşteri yorumlarını okuyun veya deneyiminizi paylaşın. E-posta adresiniz gösterilmez.", form: "Yorum gönder", rating: "Puan", body: "Deneyiminiz", placeholder: "Hangi hizmeti kullandınız?", submit: "İncelemeye gönder", empty: "Henüz yayınlanan yorum yok.", login: "Yorum için giriş yapın" },
  fr: { eyebrow: "Avis réels · Modérés avant publication", title: "Partagez votre expérience Blue Sass", intro: "Lisez ou partagez des avis. Votre e-mail n’est jamais affiché.", form: "Envoyer un avis", rating: "Note", body: "Votre expérience", placeholder: "Quel service avez-vous utilisé ?", submit: "Envoyer pour validation", empty: "Aucun avis publié pour le moment.", login: "Connectez-vous pour laisser un avis" },
  es: { eyebrow: "Opiniones reales · Moderadas", title: "Comparta su experiencia Blue Sass", intro: "Lea o comparta opiniones. Nunca mostramos su correo.", form: "Enviar opinión", rating: "Valoración", body: "Su experiencia", placeholder: "¿Qué servicio utilizó?", submit: "Enviar para revisión", empty: "Aún no hay opiniones publicadas.", login: "Inicie sesión para opinar" },
} as const;

export function ReviewsBoard({ locale, reviews, signedIn }: { locale: Locale; reviews: Review[]; signedIn: boolean }) {
  const c = copy[locale];
  const [state, action, pending] = useActionState(submitReviewAction, { ok: false, message: "" } satisfies ReviewState);
  return <main className="bg-base text-black"><section className="border-b border-black/10 bg-black py-20 text-white sm:py-28"><div className="container-x"><p className="font-mono text-xs uppercase tracking-[.25em] text-white/55">{c.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-tight text-white sm:text-7xl">{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">{c.intro}</p></div></section><section className="container-x grid gap-10 py-14 lg:grid-cols-[.72fr_1.28fr] lg:py-20"><aside className="h-fit rounded-[2rem] border border-black bg-white p-6 shadow-xl sm:p-8"><MessageSquareQuote className="size-9"/><h2 className="mt-6 text-2xl font-black">{c.form}</h2>{signedIn ? <form action={action} className="mt-7 space-y-5"><input type="hidden" name="locale" value={locale}/><div><Label>{c.rating}</Label><Select name="rating" defaultValue="5"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[5,4,3,2,1].map(value=><SelectItem key={value} value={String(value)}>{value} / 5</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="review-body">{c.body}</Label><Textarea id="review-body" name="body" required minLength={20} maxLength={1200} rows={7} placeholder={c.placeholder}/></div>{state.message ? <Alert variant={state.ok ? "success" : "destructive"}>{state.message}</Alert> : null}<Button type="submit" variant="neon" className="w-full" disabled={pending}><Send className="size-4"/>{pending ? "…" : c.submit}</Button></form> : <Button asChild variant="neon" className="mt-7 w-full"><a href={`/${locale}/login?next=/${locale}/reviews`}>{c.login}</a></Button>}</aside><div>{reviews.length ? <div className="grid gap-4 sm:grid-cols-2">{reviews.map(review=><article key={review.id} className="rounded-3xl border border-black/10 bg-white p-6 shadow-sm"><div className="flex gap-1" aria-label={`${review.rating}/5`}>{Array.from({length:5},(_,index)=><Star key={index} className={`size-4 ${index < review.rating ? "fill-black text-black" : "text-black/15"}`}/>)}</div><blockquote className="mt-6 whitespace-pre-wrap text-base leading-8 text-black/75">“{review.body}”</blockquote><footer className="mt-7 border-t border-black/10 pt-4"><strong className="block">{review.displayName}</strong>{review.company ? <span className="text-xs text-ink-low">{review.company}</span> : null}</footer></article>)}</div> : <p className="rounded-3xl border border-dashed border-black/20 p-10 text-center leading-8 text-ink-low">{c.empty}</p>}</div></section></main>;
}
