import { BarChart3, Bell, Bot, Globe2, Layers3, MessageSquareText, Monitor, Package, Palette, Search, ShoppingBag, Smartphone, Sparkles, Users } from "lucide-react";
import type { ServiceTemplate } from "@/lib/service-templates";
import { cn } from "@/lib/utils";

function Lines({ light = false }: { light?: boolean }) {
  return <div className={cn("space-y-1 text-[7px] leading-relaxed", light ? "text-white/55" : "text-black/55")}><p>Strategy, design and development</p><p className="opacity-65">Built for clarity and measurable growth</p></div>;
}
function BrowserBar({ dark = false }: { dark?: boolean }) {
  return <div className={cn("flex items-center gap-1.5 border-b px-3 py-2", dark ? "border-white/10" : "border-black/10")}><i className="size-1.5 rounded-full bg-current opacity-25"/><i className="size-1.5 rounded-full bg-current opacity-25"/><i className="size-1.5 rounded-full bg-current opacity-25"/><span className={cn("ms-2 h-3 flex-1 rounded-full", dark ? "bg-white/8" : "bg-black/5")}/></div>;
}
function WebsitePreview({ alt }: { alt: boolean }) {
  return <div className={cn("h-full overflow-hidden rounded-xl border", alt ? "border-white/10 bg-[#090b10] text-white" : "border-black/10 bg-[#f3efe8] text-black")}><BrowserBar dark={alt}/><div className="grid h-[calc(100%-29px)] grid-cols-[1.15fr_.85fr] gap-4 p-4"><div className="flex flex-col justify-center"><span className={cn("mb-3 w-fit rounded-full px-2 py-1 text-[7px] font-bold", alt ? "bg-white text-black" : "bg-black text-white")}>BLUE SASS</span><p className="max-w-40 text-lg font-black leading-tight">Digital ideas, made useful.</p><div className="mt-3"><Lines light={alt}/></div><span className={cn("mt-4 h-7 w-24 rounded-full", alt ? "bg-white" : "bg-black")}/></div><div className="relative overflow-hidden rounded-xl border border-current/10 bg-current/5"><Globe2 className="absolute left-1/2 top-1/2 size-16 -translate-x-1/2 -translate-y-1/2 opacity-30"/><i className="absolute -end-4 -top-4 size-20 rounded-full border border-current/15"/><i className="absolute -bottom-8 -start-4 size-24 rounded-full border border-current/10"/></div></div></div>;
}
function PhonePreview({ ios, alt }: { ios: boolean; alt: boolean }) {
  return <div className={cn("relative flex h-full items-center justify-center overflow-hidden rounded-xl", alt ? "bg-[#10141c]" : "bg-[#e7eef5]")}><i className="absolute -end-12 top-2 size-36 rounded-full bg-[#1769e0]/15"/><div className={cn("relative h-[92%] w-[42%] min-w-28 rounded-[1.7rem] border-[5px] p-2 shadow-2xl transition-transform duration-500 group-hover:-translate-y-1 group-hover:rotate-1", alt ? "border-white/80 bg-black text-white" : "border-black bg-white text-black")}><div className="mx-auto mb-3 h-1.5 w-10 rounded-full bg-current opacity-25"/><div className="flex items-center justify-between"><span className="text-[8px] font-bold">{ios ? "iOS" : "Android"}</span><Bell className="size-3"/></div><div className={cn("mt-3 rounded-xl p-3", alt ? "bg-white/10" : "bg-black text-white")}><Sparkles className="size-4"/><p className="mt-2 text-[9px] font-bold">Smart workspace</p></div><div className="mt-3 grid grid-cols-2 gap-2">{[1,2,3,4].map(i=><span key={i} className={cn("h-9 rounded-lg", alt ? "bg-white/8" : "bg-black/5")}/>)}</div><div className="absolute inset-x-4 bottom-3 flex justify-around"><i className="size-2 rounded-full bg-current opacity-50"/><i className="size-2 rounded-full bg-current opacity-20"/><i className="size-2 rounded-full bg-current opacity-20"/></div></div><Smartphone className="absolute bottom-4 end-5 size-8 opacity-15"/></div>;
}
function DashboardPreview({ alt, erp = false }: { alt: boolean; erp?: boolean }) {
  return <div className={cn("flex h-full overflow-hidden rounded-xl border", alt ? "border-white/10 bg-[#0a0d12] text-white" : "border-black/10 bg-[#eef1f4] text-black")}><aside className={cn("w-12 border-e p-2", alt ? "border-white/10 bg-white/4" : "border-black/10 bg-white")}><span className="grid size-7 place-items-center rounded-lg bg-[#1769e0] text-white"><Monitor className="size-3.5"/></span><div className="mt-5 space-y-2">{[1,2,3,4].map(i=><i key={i} className="block h-5 rounded bg-current opacity-[.07]"/>)}</div></aside><div className="min-w-0 flex-1 p-3"><div className="flex items-center justify-between"><strong className="text-[9px]">{erp ? "Operations" : "Desktop workspace"}</strong><Search className="size-3 opacity-50"/></div><div className="mt-3 grid grid-cols-3 gap-2">{["72%","128","€24k"].map((value)=><span key={value} className={cn("rounded-lg border p-2 text-[8px] font-bold", alt ? "border-white/10 bg-white/5" : "border-black/8 bg-white")}><i className="mb-2 block h-1 w-5 rounded bg-[#1769e0]"/>{value}</span>)}</div><div className={cn("mt-2 flex h-20 items-end gap-1 rounded-lg border p-2", alt ? "border-white/10" : "border-black/8 bg-white")}>{[40,70,50,88,64,95,75].map((height,index)=><i key={index} className="flex-1 rounded-t bg-[#1769e0]/70" style={{height:`${height}%`}}/>)}</div><div className="mt-2 flex items-center gap-2 text-[8px]"><Users className="size-3"/><BarChart3 className="size-3 opacity-40"/></div></div></div>;
}
function StorePreview({ alt }: { alt: boolean }) {
  return <div className={cn("h-full overflow-hidden rounded-xl border", alt ? "border-white/10 bg-[#0c0c0c] text-white" : "border-black/10 bg-[#faf8f2] text-black")}><BrowserBar dark={alt}/><div className="flex items-center justify-between px-4 pt-3"><strong className="text-[9px] tracking-[.2em]">ATELIER</strong><ShoppingBag className="size-4"/></div><div className="mt-3 grid grid-cols-3 gap-2 px-3">{[1,2,3].map((item)=><div key={item}><span className={cn("grid aspect-[.8] place-items-center rounded-lg", alt ? "bg-white/8" : "bg-[#e9e1d6]")}><Package className="size-7 opacity-30 transition-transform duration-500 group-hover:-translate-y-1"/></span><i className="mt-2 block h-1.5 w-4/5 rounded bg-current opacity-20"/><i className="mt-1 block h-1.5 w-1/3 rounded bg-current opacity-10"/></div>)}</div></div>;
}
function AiPreview({ alt }: { alt: boolean }) {
  return <div className={cn("grid h-full grid-cols-[.8fr_1.2fr] overflow-hidden rounded-xl border", alt ? "border-white/10 bg-[#080b11] text-white" : "border-black/10 bg-white text-black")}><div className={cn("border-e p-3", alt ? "border-white/10" : "border-black/10 bg-[#f4f5f7]")}><span className="flex items-center gap-2 text-[9px] font-bold"><Bot className="size-4"/>Automations</span><div className="mt-4 space-y-2">{[1,2,3,4].map(item=><i key={item} className="block h-7 rounded-lg border border-current/10 bg-current/5"/>)}</div></div><div className="relative p-3"><span className="text-[8px] opacity-50">AI ASSISTANT</span><div className="mt-4 space-y-3"><div className="ms-auto w-4/5 rounded-xl rounded-ee-sm bg-[#1769e0] p-2 text-[8px] text-white">Build the next workflow</div><div className={cn("w-5/6 rounded-xl rounded-es-sm p-2 text-[8px]",alt?"bg-white/10":"bg-black/5")}><MessageSquareText className="mb-2 size-3"/><Lines light={alt}/></div></div><span className={cn("absolute inset-x-3 bottom-3 h-8 rounded-full border",alt?"border-white/15":"border-black/10")}/></div></div>;
}
function BrandPreview({ alt }: { alt: boolean }) {
  return <div className={cn("grid h-full grid-cols-2 gap-2 overflow-hidden rounded-xl p-3", alt ? "bg-[#090909] text-white" : "bg-[#eee9df] text-black")}><div className={cn("flex flex-col justify-between rounded-xl p-3",alt?"bg-white text-black":"bg-black text-white")}><Palette className="size-5"/><strong className="text-2xl leading-none">B/S</strong><span className="text-[7px] tracking-[.24em]">BRAND SYSTEM</span></div><div className="grid grid-rows-2 gap-2"><div className={cn("relative overflow-hidden rounded-xl",alt?"bg-[#1769e0]":"bg-white")}><i className="absolute left-1/2 top-1/2 size-16 -translate-x-1/2 -translate-y-1/2 rounded-full border-[10px] border-current opacity-25 transition-transform duration-700 group-hover:rotate-90"/></div><div className="grid grid-cols-3 gap-2">{["#05","Aa","UI"].map(value=><span key={value} className="grid place-items-center rounded-lg border border-current/10 bg-current/5 text-[9px] font-bold">{value}</span>)}</div></div></div>;
}

export function TemplateLivePreview({ item, expanded = false, showLabels = true }: { item: ServiceTemplate; expanded?: boolean; showLabels?: boolean }) {
  const alt = Boolean(item.variant);
  let content;
  if (item.service === "web") content = <WebsitePreview alt={alt}/>;
  else if (item.service === "android") content = <PhonePreview ios={false} alt={alt}/>;
  else if (item.service === "ios") content = <PhonePreview ios alt={alt}/>;
  else if (item.service === "windows") content = <DashboardPreview alt={alt}/>;
  else if (item.service === "store") content = <StorePreview alt={alt}/>;
  else if (item.service === "erp") content = <DashboardPreview alt={alt} erp/>;
  else if (item.service === "ai") content = <AiPreview alt={alt}/>;
  else content = <BrandPreview alt={alt}/>;
  return <div className={cn("group relative w-full overflow-hidden rounded-2xl bg-[#151922] p-2", expanded ? "h-[min(58vh,520px)]" : "h-64")}><div className="absolute inset-x-10 top-0 h-px bg-gradient-to-r from-transparent via-white/40 to-transparent"/><div className="h-full transition-transform duration-500 ease-out group-hover:scale-[1.015]">{content}</div>{showLabels && <><div className="pointer-events-none absolute bottom-3 start-3 max-w-[65%] truncate rounded-full border border-white/10 bg-black/70 px-2.5 py-1 text-[8px] font-semibold text-white backdrop-blur">{item.name}</div><div className="pointer-events-none absolute bottom-3 end-3 flex items-center gap-1 rounded-full border border-white/10 bg-black/70 px-2 py-1 text-[8px] font-semibold text-white backdrop-blur"><Layers3 className="size-2.5"/>LIVE UI</div></>}</div>;
}
