"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowUpRight, CheckCircle2, Globe, Layers, ShieldCheck } from "lucide-react";
import { useI18n } from "@/components/providers";
import { Button } from "@/components/ui/button";
import { websiteNames, websitePackages } from "@/lib/website-packages";
import { applyImplementationDiscount, formatEUR, getImplementationPromotion } from "@/lib/pricing";
import { websiteWorkflows } from "@/lib/i18n/website-workflows";
const promotionMessage = {
 ar: (percent:number) => `عرض اليوم: خصم ${percent}% على تنفيذ المشروع`,
 en: (percent:number) => `${percent}% off project implementation today`,
 nl: (percent:number) => `Vandaag ${percent}% korting op projectrealisatie`,
 de: (percent:number) => `Heute ${percent}% Rabatt auf die Projektumsetzung`,
 tr: (percent:number) => `Bugün proje geliştirmede %${percent} indirim`,
 fr: (percent:number) => `Aujourd’hui, ${percent}% de remise sur la réalisation`,
 es: (percent:number) => `Hoy, ${percent}% de descuento en el desarrollo`,
} as const;
export function PromotionBanner() {
 const { locale, t } = useI18n(); const c = t.pricing; const pathname = usePathname(); const promotion = getImplementationPromotion();
 const message = promotionMessage[locale](promotion.percent);
 const reverse = (pathname.length + promotion.percent) % 2 === 0;
 return <section className="bg-black py-9 text-white"><div className={`container-x flex flex-col gap-6 sm:items-center sm:justify-between ${reverse ? "sm:flex-row-reverse" : "sm:flex-row"}`}><div className={reverse ? "sm:text-end" : ""}><span className="inline-flex rounded-full bg-neon-cyan px-3 py-1 text-xs font-bold text-black">{promotion.id}</span><h2 className="mt-3 text-2xl font-bold text-white">{message}</h2><p className="mt-3 max-w-3xl text-xs leading-6 text-white/75">{c.terms}</p></div><Button asChild variant="neon" className="shrink-0"><Link href={`/${locale}/services#pricing`}>{c.nav}<ArrowUpRight className="size-4"/></Link></Button></div></section>;
}
export function WebsitePricing({ embedded = false }: { embedded?: boolean }) {
 const { locale, t } = useI18n(); const c = t.pricing; const [filter,setFilter] = useState("all");
 const categories = ["all","essential","commerce","platform"] as const;
 return <>{!embedded && <><section className="container-x pt-16 pb-10"><p className="text-sm font-semibold text-neon-blue">{c.nav}</p><h1 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-3xl leading-8 text-ink-low">{c.intro}</p></section><PromotionBanner/></>}<section id="pricing" className="container-x py-16">{embedded && <div className="mb-10"><p className="text-sm font-semibold text-neon-blue">{c.nav}</p><h2 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">{c.title}</h2><p className="mt-5 max-w-3xl leading-8 text-ink-low">{c.intro}</p></div>}<p className="max-w-4xl text-sm leading-7 text-ink-low">{c.tax}</p><div className="my-7 flex flex-wrap gap-2">{categories.map(cat => <Button key={cat} variant={filter===cat?"neon":"outline"} aria-pressed={filter===cat} onClick={() => setFilter(cat)}>{c[cat]}</Button>)}</div>
 <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{websitePackages.map((pack,index) => ({pack,index})).filter(({pack})=>filter==="all"||pack.category===filter).map(({pack,index})=><article key={pack.id} data-package={pack.id} className="flex flex-col rounded-3xl border border-black/15 bg-white p-6"><div className="flex justify-between"><Globe className="size-6 text-neon-blue"/><span className="font-mono text-xs text-ink-low">{String(index+1).padStart(2,"0")}</span></div><h2 className="mt-5 text-xl font-bold">{websiteNames[locale][index]}</h2><p className="mt-3 text-sm leading-7 text-ink-low">{websiteWorkflows[locale][index]}</p><p className="mt-5 text-xs text-ink-low">{c.from}</p><p className="mt-2 text-4xl font-bold">{formatEUR(applyImplementationDiscount(pack.low),locale)}</p><p className="mt-3 text-xs leading-6 text-ink-low">{c.range}<br/>{formatEUR(applyImplementationDiscount(pack.low),locale)} – {formatEUR(applyImplementationDiscount(pack.high),locale)}{pack.custom?"+":""}</p><dl className="my-6 space-y-3 border-y border-black/10 py-5 text-xs">{(["login","payment","cms"] as const).map(key=><div key={key} className="flex justify-between gap-3"><dt className="text-ink-low">{c[key]}</dt><dd className="text-end font-semibold">{c[pack[key]]}</dd></div>)}</dl><p className="font-semibold text-sm">{c.units} {pack.units}</p><p className="mt-3 text-xs leading-6 text-ink-low">{pack.custom?c.custom:c.scope}</p><ul className="my-4 space-y-2">{pack.features.map(key=><li key={key} className="flex gap-2 text-xs"><CheckCircle2 className="size-3.5 shrink-0 text-neon-blue"/>{t.quote.features[key]}</li>)}</ul><Button asChild variant="neon" className="mt-auto w-full"><Link href={`/${locale}/quote?kind=${pack.id}&type=${pack.type}`}>{c.choose}<ArrowUpRight className="size-4"/></Link></Button></article>)}</div></section>
 <section className="container-x py-12"><h2 className="text-3xl font-bold">{c.recurring}</h2><div className="mt-7 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-black/15 bg-white p-6"><ShieldCheck className="size-6"/><h3 className="mt-4 font-bold">{c.hosting}</h3><p className="mt-3 text-sm">€25 / €65 / €150 · {c.monthly}</p><Button asChild variant="outline" className="mt-5"><Link href={`/${locale}/subscriptions`}>{t.nav.services} · {c.hosting}</Link></Button></article><article className="rounded-2xl border border-black/15 bg-white p-6"><h3 className="font-bold">{c.domains}</h3><p className="mt-3 text-sm leading-7 text-ink-low">{c.external}</p></article><article className="rounded-2xl border border-black/15 bg-white p-6"><h3 className="font-bold">{c.processing}</h3><p className="mt-3 text-sm leading-7 text-ink-low">{c.stripe}</p><a href="https://stripe.com/nl/pricing" target="_blank" rel="noopener noreferrer" className="mt-4 inline-block text-sm font-semibold text-neon-blue underline">Stripe ↗</a></article></div></section>
 <section className="container-x py-12"><h2 className="text-3xl font-bold">{c.methods}</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[[c.template,c.templateBody],[c.builders,c.buildersBody],[c.bespoke,c.bespokeBody]].map(([title,body])=><article key={title} className="rounded-2xl bg-black p-6 text-white"><Layers className="size-6 text-neon-cyan"/><h3 className="mt-5 text-lg font-bold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-white/75">{body}</p></article>)}</div><p className="mt-7 text-xs leading-6 text-ink-low">{c.date} · {c.disclaimer}</p></section></>;
}
