"use client";
import { useActionState } from "react";
import { useI18n } from "@/components/providers";
import { workspaceCopy } from "@/lib/i18n/workspace-copy";
import { platformCopy } from "@/lib/i18n/platform-tools";
import type { ProjectAgreement } from "@/lib/project-agreement";
import { saveProjectAgreement, acceptProjectAgreement, requestProjectDecision, answerProjectDecision } from "@/app/actions/project-workspace";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
const initial = { ok: false, code: "" };
type Decision = { id: string; title: string; detail: string; priceCents: number | null; extraDays: number | null; state: string; response: string | null; createdAt: string };
function Result({ code }: { code: string }) { const { locale } = useI18n(); const p = platformCopy(locale); const c = workspaceCopy(locale); return <p role="status" className="mt-3 text-sm leading-7 text-white/70">{code === "AGREEMENT_LOCKED" ? c.locked : code ? p.errors[code as keyof typeof p.errors] ?? p.errors.INVALID_INPUT : ""}</p>; }
function AgreementEditor({ projectId, agreement }: { projectId: string; agreement: ProjectAgreement | null }) {
  const { locale } = useI18n(); const c = workspaceCopy(locale); const [state, action, pending] = useActionState(saveProjectAgreement, initial);
  return <form action={action} className="space-y-4"><Input type="hidden" name="projectId" value={projectId}/><div><Label htmlFor="scope-included">{c.included}</Label><Textarea id="scope-included" name="included" required minLength={3} maxLength={4000} rows={4} defaultValue={agreement?.included.join("\n")}/></div><div><Label htmlFor="scope-excluded">{c.excluded}</Label><Textarea id="scope-excluded" name="excluded" maxLength={4000} rows={3} defaultValue={agreement?.excluded.join("\n")}/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="scope-rounds">{c.rounds}</Label><Input id="scope-rounds" name="revisionRounds" type="number" min={0} max={20} required defaultValue={agreement?.revisionRounds}/></div><div><Label htmlFor="scope-days">{c.days}</Label><Input id="scope-days" name="deliveryDays" type="number" min={2} max={365} required defaultValue={agreement?.deliveryDays}/></div></div><Button type="submit" variant="neon" disabled={pending}>{c.save}</Button><Result code={state.code}/></form>;
}
function AgreementApproval({ projectId, agreement }: { projectId: string; agreement: ProjectAgreement }) {
  const { locale } = useI18n(); const c = workspaceCopy(locale); const [state, action, pending] = useActionState(acceptProjectAgreement, initial);
  return <form action={action} className="mt-6 space-y-4"><Input type="hidden" name="projectId" value={projectId}/><Input type="hidden" name="version" value={agreement.version}/><Label htmlFor="scope-consent" className="flex items-start gap-3 text-sm leading-7"><Checkbox id="scope-consent" name="consent" value="yes" required className="mt-1"/>{c.scopeConsent}</Label><Button type="submit" variant="neon" disabled={pending || !agreement.priceCents}>{c.accept}</Button><Result code={state.code}/></form>;
}
function DecisionRequest({ projectId, canPriceChanges }: { projectId: string; canPriceChanges: boolean }) {
  const { locale } = useI18n(); const c = workspaceCopy(locale); const [state, action, pending] = useActionState(requestProjectDecision, initial);
  return <form action={action} className="mt-5 space-y-4"><Input type="hidden" name="projectId" value={projectId}/><div><Label htmlFor="decision-title">{c.title}</Label><Input id="decision-title" name="title" required minLength={3} maxLength={120}/></div><div><Label htmlFor="decision-detail">{c.detail}</Label><Textarea id="decision-detail" name="detail" required minLength={3} maxLength={3000} rows={3}/></div>{canPriceChanges && <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="change-price">{c.approvedPrice} · EUR</Label><Input id="change-price" name="price" type="number" min={0} max={999999} step="0.01"/></div><div><Label htmlFor="change-days">+ {c.days}</Label><Input id="change-days" name="extraDays" type="number" min={0} max={999}/></div></div>}<Button type="submit" variant="outline" disabled={pending}>{c.request}</Button><Result code={state.code}/></form>;
}
function DecisionAnswer({ decision }: { decision: Decision }) {
  const { locale } = useI18n(); const c = workspaceCopy(locale); const [state, action, pending] = useActionState(answerProjectDecision, initial);
  return <form action={action} className="mt-4 space-y-3"><Input type="hidden" name="id" value={decision.id}/><Label htmlFor={`response-${decision.id}`}>{c.response}</Label><Textarea id={`response-${decision.id}`} name="response" maxLength={2000} rows={2}/><div className="flex flex-wrap gap-3"><Button type="submit" variant="neon" name="state" value="approved" disabled={pending}>{c.approve}</Button><Button type="submit" variant="outline" name="state" value="changes_requested" disabled={pending}>{c.changes}</Button></div><Result code={state.code}/></form>;
}
export function ProjectWorkspace({ projectId, agreement, decisions, canManageOffer, canRequestReview, canPriceChanges, isClient, editable, updatedAt }: { projectId: string; agreement: ProjectAgreement | null; decisions: Decision[]; canManageOffer: boolean; canRequestReview: boolean; canPriceChanges: boolean; isClient: boolean; editable: boolean; updatedAt: string }) {
  const { locale } = useI18n(); const c = workspaceCopy(locale);
  const pendingDecisions = decisions.filter(row => row.state === "pending");
  return <section className="container-x tool-surface mt-7 rounded-2xl p-5 sm:p-7"><h2 className="text-2xl font-semibold">{c.needsYou}</h2><p className="mt-3 text-xs text-white/60" dir="auto">{c.lastUpdate}: {updatedAt.slice(0, 19).replace("T", " ")} UTC</p>{!pendingDecisions.length && (!agreement || agreement.acceptedAt) && <p className="mt-3 text-sm text-white/65">{c.empty}</p>}
    {(agreement || canManageOffer) && <Card className="tool-card mt-6"><CardHeader><CardTitle className="text-white">{c.scope}</CardTitle></CardHeader><CardContent>{agreement && <><div className="grid gap-5 md:grid-cols-2"><div><h3 className="text-sm font-semibold">{c.included}</h3><ul className="mt-3 space-y-2 text-sm leading-7 text-white/70">{agreement.included.map((point, index) => <li key={index}>{point}</li>)}</ul></div><div><h3 className="text-sm font-semibold">{c.excluded}</h3><ul className="mt-3 space-y-2 text-sm leading-7 text-white/70">{agreement.excluded.map((point, index) => <li key={index}>{point}</li>)}</ul></div></div><dl className="mt-6 grid gap-3 sm:grid-cols-3"><div><dt className="text-xs text-white/60">{c.approvedPrice}</dt><dd className="mt-2 font-semibold">{agreement.priceCents === null ? "—" : `€${(agreement.priceCents / 100).toFixed(2)}`}</dd></div><div><dt className="text-xs text-white/60">{c.rounds}</dt><dd className="mt-2">{agreement.revisionRounds}</dd></div><div><dt className="text-xs text-white/60">{c.days}</dt><dd className="mt-2">{agreement.deliveryDays}</dd></div></dl><p className="mt-5 text-sm">{agreement.acceptedAt ? c.approved : c.pending} · #{agreement.version}</p>{isClient && !agreement.acceptedAt && <AgreementApproval projectId={projectId} agreement={agreement}/>}</>}{canManageOffer && editable && <details className="mt-6"><summary className="cursor-pointer text-sm font-semibold">{c.save}</summary><div className="mt-5"><AgreementEditor projectId={projectId} agreement={agreement}/></div></details>}<p className="mt-5 text-xs leading-7 text-white/55">{c.timing}</p><p className="mt-3 text-xs leading-7 text-white/55">{c.separateChange}</p></CardContent></Card>}
    <Card className="tool-card mt-6"><CardHeader><CardTitle className="text-white">{c.decisions}</CardTitle></CardHeader><CardContent><ul className="space-y-4">{decisions.map(row => <li key={row.id} className="rounded-xl border border-white/20 p-4"><h3 className="text-sm font-semibold">{row.title}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-white/70">{row.detail}</p>{row.priceCents !== null && <p className="mt-3 text-sm">{c.approvedPrice}: €{(row.priceCents / 100).toFixed(2)}</p>}{row.extraDays !== null && <p className="mt-3 text-sm">+ {c.days}: {row.extraDays}</p>}<p className="mt-3 text-xs">{row.state === "approved" ? c.approve : row.state === "changes_requested" ? c.changes : c.pending}</p>{row.response && <p className="mt-3 whitespace-pre-wrap text-sm leading-7">{row.response}</p>}{isClient && row.state === "pending" && <DecisionAnswer decision={row}/>}</li>)}</ul>{canRequestReview && <details className="mt-5"><summary className="cursor-pointer text-sm font-semibold">{c.request}</summary><DecisionRequest projectId={projectId} canPriceChanges={canPriceChanges}/></details>}</CardContent></Card>
  </section>;
}
