"use client";
import { withExtraLocales } from "@/lib/i18n/extra-locales";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bot, Gauge, Layers3, ShieldCheck, Workflow } from "lucide-react";
import { useI18n } from "@/components/providers";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const copy = withExtraLocales({
  ar: { title: "ما الذي يجعل المنتج أقوى؟", subtitle: "تفاصيل عملية ندمجها في المشروع بدل إضافة زخارف لا تخدم الهدف.", previous: "السابق", next: "التالي", cards: [["قرار واضح قبل الكود", "نحوّل الهدف والجمهور والمحتوى إلى نطاق يمكن قياسه."], ["واجهة تقود المستخدم", "تسلسل بصري وحركة هادئة يساعدان الزائر على اتخاذ الخطوة التالية."], ["أداء وأمان من البداية", "بنية سريعة، تحقق من البيانات، وصلاحيات واضحة قبل الإطلاق."], ["لوحة متابعة حقيقية", "تشاهد حالة المشروع والدفعات والملفات والقرارات في مكان واحد."], ["قابلية للتوسع", "مكوّنات منظمة وتكاملات يمكن تطويرها مع نمو نشاطك."]] },
  en: { title: "What makes a stronger product?", subtitle: "Practical details built into the project instead of decoration without purpose.", previous: "Previous", next: "Next", cards: [["Clarity before code", "Goals, audience and content become a measurable scope."], ["An interface that guides", "Visual hierarchy and calm motion help visitors take the next step."], ["Performance and security", "Fast foundations, validation and clear permissions from day one."], ["A real client workspace", "Track project status, payments, files and decisions in one place."], ["Ready to scale", "Organised components and integrations that grow with the business."]] },
  nl: { title: "Wat maakt een product sterker?", subtitle: "Praktische details in het project, geen decoratie zonder doel.", previous: "Vorige", next: "Volgende", cards: [["Duidelijkheid vóór code", "Doelen, doelgroep en content worden een meetbare scope."], ["Een interface die leidt", "Hiërarchie en rustige beweging sturen de bezoeker."], ["Prestaties en veiligheid", "Een snelle basis, validatie en heldere rechten."], ["Een echte klantomgeving", "Status, betalingen, bestanden en besluiten op één plek."], ["Klaar om te groeien", "Geordende componenten en uitbreidbare koppelingen."]] },
  de: { title: "Was macht ein Produkt stärker?", subtitle: "Praktische Details statt Dekoration ohne Zweck.", previous: "Zurück", next: "Weiter", cards: [["Klarheit vor Code", "Ziele, Zielgruppe und Inhalte werden messbar."], ["Eine führende Oberfläche", "Hierarchie und ruhige Bewegung leiten Nutzer."], ["Leistung und Sicherheit", "Schnelle Basis, Validierung und klare Rechte."], ["Echter Kundenbereich", "Status, Zahlungen, Dateien und Entscheidungen an einem Ort."], ["Bereit zu wachsen", "Geordnete Komponenten und erweiterbare Integrationen."]] },
  tr: { title: "Ürünü daha güçlü yapan nedir?", subtitle: "Amaçsız süsler yerine projeye dahil edilen gerçek ayrıntılar.", previous: "Önceki", next: "Sonraki", cards: [["Koddan önce netlik", "Hedefler, kitle ve içerik ölçülebilir kapsama dönüşür."], ["Yönlendiren arayüz", "Hiyerarşi ve sakin hareket kullanıcıya yol gösterir."], ["Performans ve güvenlik", "Hızlı temel, doğrulama ve net yetkiler."], ["Gerçek müşteri alanı", "Durum, ödeme, dosya ve kararlar tek yerde."], ["Büyümeye hazır", "Düzenli bileşenler ve genişleyebilir entegrasyonlar."]] },
  fr: { title: "Qu’est-ce qui renforce un produit ?", subtitle: "Des détails utiles intégrés au projet, sans décoration gratuite.", previous: "Précédent", next: "Suivant", cards: [["Clarté avant le code", "Objectifs, public et contenus deviennent mesurables."], ["Une interface qui guide", "Hiérarchie et mouvement calme orientent le visiteur."], ["Performance et sécurité", "Base rapide, validation et droits clairs."], ["Un vrai espace client", "Suivi, paiements, fichiers et décisions au même endroit."], ["Prêt à évoluer", "Composants organisés et intégrations extensibles."]] },
  es: { title: "¿Qué hace más fuerte un producto?", subtitle: "Detalles útiles integrados, sin decoración que no cumpla un objetivo.", previous: "Anterior", next: "Siguiente", cards: [["Claridad antes del código", "Objetivos, público y contenido se convierten en alcance medible."], ["Una interfaz que guía", "Jerarquía y movimiento sereno orientan al visitante."], ["Rendimiento y seguridad", "Base rápida, validación y permisos claros."], ["Un área real de cliente", "Estado, pagos, archivos y decisiones en un solo lugar."], ["Preparado para crecer", "Componentes organizados e integraciones ampliables."]] },
} as const);

const icons = [Workflow, Layers3, ShieldCheck, Gauge, Bot];

export function StaggerShowcase() {
  const { locale } = useI18n();
  const c = copy[locale];
  const [active, setActive] = useState(0);
  const [compact, setCompact] = useState(false);
  useEffect(() => { const update = () => setCompact(window.innerWidth < 640); update(); window.addEventListener("resize", update); return () => window.removeEventListener("resize", update); }, []);
  const count = c.cards.length;
  const move = (step: number) => setActive((value) => (value + step + count) % count);
  const ordered = c.cards.map((card, index) => ({ card, index })).sort((a, b) => (a.index === active ? 1 : b.index === active ? -1 : 0));
  return <section className="overflow-hidden bg-white py-20"><div className="container-x text-center"><h2 className="mx-auto max-w-3xl text-4xl font-bold sm:text-6xl">{c.title}</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-ink-low">{c.subtitle}</p></div><div className="relative isolate mx-auto mt-4 h-[540px] max-w-[1200px] overflow-hidden sm:h-[560px]">
    {ordered.map(({ card: [title, body], index }) => { const raw = (index - active + count) % count; const position = raw > count / 2 ? raw - count : raw; const center = position === 0; const Icon = icons[index]; return <Button key={title} variant="unstyled" size="auto" onClick={()=>setActive(index)} aria-label={title} aria-current={center ? "true" : undefined} className={cn("absolute left-1/2 top-1/2 block min-h-[360px] w-[min(86vw,380px)] whitespace-normal break-words border-2 p-7 text-start transition-[background-color,border-color,opacity] duration-500 sm:min-h-[340px]", center ? "z-overlay border-black bg-black text-white shadow-2xl" : "z-stage border-black/15 bg-base text-black")} style={{ clipPath: "polygon(36px 0,100% 0,100% calc(100% - 36px),calc(100% - 36px) 100%,0 100%,0 36px)", transform: `translate(-50%,-50%) translateX(${position * (compact ? 210 : 285)}px) translateY(${center ? -20 : position % 2 ? 18 : -8}px) rotate(${center ? 0 : position % 2 ? 2.2 : -2.2}deg) scale(${center ? 1 : .92})`, opacity: Math.abs(position) > 2 ? 0 : center ? 1 : compact ? .12 : .36, pointerEvents: Math.abs(position) > 2 ? "none" : "auto" }}><span className={cn("grid size-12 place-items-center rounded-full", center ? "bg-white text-black" : "bg-black text-white")}><Icon className="size-5"/></span><span className="mt-7 block font-mono text-xs opacity-45">0{index+1}</span><strong className="mt-3 block text-2xl leading-tight">{title}</strong><span className={cn("mt-4 block text-sm leading-7", center ? "text-white/75" : "text-black/55")}>{body}</span></Button>; })}
    <div className="absolute inset-x-0 bottom-4 z-content flex justify-center gap-2"><Button variant="outline" size="icon" className="size-12 rounded-full bg-white" onClick={()=>move(locale === "ar" ? 1 : -1)} aria-label={c.previous}><ArrowLeft className="size-4 flip-x"/></Button><Button variant="neon" size="icon" className="size-12 rounded-full" onClick={()=>move(locale === "ar" ? -1 : 1)} aria-label={c.next}><ArrowRight className="size-4 flip-x"/></Button></div>
  </div></section>;
}
