import type { Locale } from "@/lib/i18n";

export const serviceSlugs = ["web", "android", "ios", "windows", "store", "erp", "ai", "design"] as const;
export type ServiceSlug = typeof serviceSlugs[number];
export const serviceQuoteTypes = ["web", "mobile", "mobile", "erp", "ecommerce", "erp", "ai", "brand"];
const rows: Record<Locale, string[]> = {
  ar: ["مواقع الويب|موقع يعرض شركتك ويحوّل الزيارات إلى طلبات.|صفحات متجاوبة،إدارة المحتوى،نماذج التواصل", "تطبيقات أندرويد|خدماتك في متناول عملائك على أندرويد.|حسابات المستخدمين،إشعارات،ربط واجهات البيانات", "تطبيقات آيفون|تجربة مصممة لشاشات آيفون وأسلوب استخدامها.|واجهات iOS،تسجيل الدخول،تجهيز للنشر", "برامج ويندوز|أدوات مكتبية لتنظيم عمل فريقك اليومي.|إدارة الملفات،تقارير قابلة للتصدير،صلاحيات الفريق", "المتاجر الإلكترونية|اعرض منتجاتك واستقبل الطلبات في مكان واحد.|كتالوج المنتجات،سلة المشتريات،ربط الدفع والشحن", "أنظمة إدارة الأعمال|تابع العملاء والطلبات والعمليات من لوحة واحدة.|إدارة العملاء،تتبع المهام،تقارير الأداء", "الذكاء الاصطناعي والأتمتة|اختصر المهام المتكررة واربط أدوات عملك.|مساعد خدمة العملاء،ربط الخدمات،معالجة المستندات", "تصميم الواجهات والهوية|تصميم واضح ومتناسق قبل بدء البرمجة.|شعار وهوية،نموذج تفاعلي،تصميم للجوال"] ,
  en: ["Websites|Turn your business into a clear, accessible online experience.|Responsive pages,Content management,Contact forms", "Android apps|Bring your services to your customers’ Android devices.|User accounts,Notifications,API integrations", "iPhone apps|An experience designed around iPhone screens and interactions.|iOS interfaces,Sign-in,Release preparation", "Windows software|Desktop tools for your team’s everyday work.|File management,Exportable reports,Team permissions", "Online stores|Showcase products and manage orders in one place.|Product catalog,Shopping cart,Payment and shipping integrations", "Business systems|Manage customers, orders and operations in one workspace.|Customer management,Task tracking,Performance reports", "AI & automation|Connect your tools and reduce repetitive work.|Support assistant,Service integrations,Document processing", "Interface & brand design|A consistent visual experience before development begins.|Logo and identity,Interactive prototype,Mobile design"],
  nl: ["Websites|Een heldere online presentatie voor uw bedrijf.|Responsieve pagina’s,Contentbeheer,Contactformulieren", "Android-apps|Uw diensten op de Android-toestellen van uw klanten.|Gebruikersaccounts,Meldingen,API-koppelingen", "iPhone-apps|Een ervaring ontworpen voor iPhone.|iOS-interfaces,Inloggen,Publicatievoorbereiding", "Windows-software|Desktoptools voor het dagelijkse werk.|Bestandsbeheer,Exporteerbare rapporten,Teamrechten", "Webwinkels|Producten en bestellingen op één plek.|Productcatalogus,Winkelwagen,Betaal- en verzendkoppelingen", "Bedrijfssystemen|Klanten en processen in één werkomgeving.|Klantbeheer,Taakbeheer,Prestatierapporten", "AI & automatisering|Verbind tools en verminder herhaalwerk.|Supportassistent,Servicekoppelingen,Documentverwerking", "Interface & huisstijl|Een samenhangend ontwerp vóór de ontwikkeling.|Logo en identiteit,Interactief prototype,Mobiel ontwerp"],
  de: ["Websites|Ein klarer Internetauftritt für Ihr Unternehmen.|Responsive Seiten,Inhaltsverwaltung,Kontaktformulare", "Android-Apps|Ihre Dienste auf den Android-Geräten Ihrer Kunden.|Benutzerkonten,Benachrichtigungen,API-Anbindung", "iPhone-Apps|Eine speziell für das iPhone entwickelte Erfahrung.|iOS-Oberflächen,Anmeldung,Vorbereitung der Veröffentlichung", "Windows-Software|Desktop-Werkzeuge für den Arbeitsalltag.|Dateiverwaltung,Exportierbare Berichte,Teamrechte", "Onlineshops|Produkte und Bestellungen an einem Ort.|Produktkatalog,Warenkorb,Zahlungs- und Versandanbindung", "Unternehmenssysteme|Kunden und Abläufe zentral verwalten.|Kundenverwaltung,Aufgabenverfolgung,Leistungsberichte", "KI & Automatisierung|Werkzeuge verbinden und Routinearbeit reduzieren.|Supportassistent,Dienstanbindungen,Dokumentenverarbeitung", "Oberflächen & Marken|Ein einheitliches Design vor der Entwicklung.|Logo und Identität,Interaktiver Prototyp,Mobiles Design"],
  tr: ["Web siteleri|İşletmeniz için anlaşılır bir dijital vitrin.|Duyarlı sayfalar,İçerik yönetimi,İletişim formları", "Android uygulamaları|Hizmetleriniz müşterilerinizin Android cihazlarında.|Kullanıcı hesapları,Bildirimler,API bağlantıları", "iPhone uygulamaları|iPhone için tasarlanmış bir deneyim.|iOS arayüzleri,Giriş,Yayına hazırlık", "Windows yazılımları|Ekibinizin günlük işleri için masaüstü araçları.|Dosya yönetimi,Dışa aktarılabilir raporlar,Ekip izinleri", "E-ticaret|Ürünler ve siparişler tek yerde.|Ürün kataloğu,Alışveriş sepeti,Ödeme ve kargo bağlantıları", "İş yönetim sistemleri|Müşterileri ve süreçleri tek yerden yönetin.|Müşteri yönetimi,Görev takibi,Performans raporları", "Yapay zekâ ve otomasyon|Araçlarınızı bağlayın ve tekrarları azaltın.|Destek asistanı,Hizmet bağlantıları,Belge işleme", "Arayüz ve marka|Geliştirmeden önce tutarlı bir tasarım.|Logo ve kimlik,Etkileşimli prototip,Mobil tasarım"],
  fr: ["Sites web|Une présence en ligne claire pour votre entreprise.|Pages adaptatives,Gestion de contenu,Formulaires de contact", "Applications Android|Vos services sur les appareils Android de vos clients.|Comptes utilisateurs,Notifications,Intégrations API", "Applications iPhone|Une expérience conçue pour iPhone.|Interfaces iOS,Connexion,Préparation à la publication", "Logiciels Windows|Des outils de bureau pour le travail quotidien.|Gestion de fichiers,Rapports exportables,Droits d’équipe", "Boutiques en ligne|Produits et commandes au même endroit.|Catalogue produits,Panier,Intégrations paiement et livraison", "Gestion d’entreprise|Centralisez vos clients et vos opérations.|Gestion clients,Suivi des tâches,Rapports de performance", "IA et automatisation|Connectez vos outils et réduisez les tâches répétitives.|Assistant support,Intégrations de services,Traitement de documents", "Interfaces et identité|Un design cohérent avant le développement.|Logo et identité,Prototype interactif,Design mobile"],
  es: ["Sitios web|Una presencia digital clara para su empresa.|Páginas adaptables,Gestión de contenido,Formularios de contacto", "Aplicaciones Android|Sus servicios en los dispositivos Android de sus clientes.|Cuentas de usuario,Notificaciones,Integraciones API", "Aplicaciones iPhone|Una experiencia diseñada para iPhone.|Interfaces iOS,Inicio de sesión,Preparación de publicación", "Software Windows|Herramientas de escritorio para el trabajo diario.|Gestión de archivos,Informes exportables,Permisos de equipo", "Tiendas en línea|Productos y pedidos en un solo lugar.|Catálogo de productos,Carrito,Integraciones de pago y envío", "Sistemas empresariales|Gestione clientes y operaciones en un mismo espacio.|Gestión de clientes,Seguimiento de tareas,Informes de rendimiento", "IA y automatización|Conecte herramientas y reduzca tareas repetitivas.|Asistente de soporte,Integraciones de servicios,Procesamiento de documentos", "Interfaces e identidad|Un diseño coherente antes de desarrollar.|Logotipo e identidad,Prototipo interactivo,Diseño móvil"],
};
export function serviceCatalog(locale: Locale) {
  return rows[locale].map((row, i) => {
    const [title, description, features] = row.split("|");
    return { slug: serviceSlugs[i], title, description, features: features.split(/[,،]/), quoteType: serviceQuoteTypes[i] };
  });
}
