import type { Locale } from "@/lib/i18n/config";
export const subscriptionDetails: Record<Locale, string[][]> = {
 ar: [["متابعة حالة الاستضافة وشهادة SSL والتنبيه عند وجود مشكلة", "استخدام ساعة الدعم لمهام صغيرة مثل تحديث نص أو معالجة خلل", "ملخص شهري بالأعمال المنفذة والملاحظات التي تحتاج قرارك", "نسخة احتياطية أسبوعية ضمن سياسة الاحتفاظ المعتمدة"], ["بيئة تجريبية لمراجعة التغييرات قبل نقلها للموقع", "تخصيص الساعات الأربع لتحديث المحتوى أو تحسين صفحات التحويل", "مراجعة مؤشرات السرعة والتحليلات لتحديد أولويات الشهر", "نسخ يومي لتقليل الفترة بين نقاط الاستعادة"], ["تخصيص الساعات العشر لتطويرات وربط خدمات وأتمتة متفق عليها", "ترتيب الطلبات حسب أثرها على نشاطك ومراجعتها تقنيًا", "أولوية التواصل والمتابعة للمشكلات والتغييرات", "خطة تحسين شهرية ضمن الوقت والنطاق المعتمدين"]],
 en: [["Monitor hosting and SSL health and flag issues", "Use the support hour for small content updates or fixes", "Monthly summary of completed work and decisions needed", "Weekly backup within the agreed retention policy"], ["Review changes in staging before publishing", "Allocate four hours to content or conversion-page improvements", "Review speed and analytics to prioritise the month", "Daily backups reduce the interval between restore points"], ["Allocate ten hours to agreed development and integrations", "Prioritise requests by business impact with technical review", "Priority communication for issues and changes", "Monthly improvement plan within approved time and scope"]],
 nl: [["Hosting en SSL controleren en problemen signaleren", "Supportuur voor kleine contentwijzigingen of reparaties", "Maandoverzicht van werk en benodigde beslissingen", "Wekelijkse back-up volgens afgesproken bewaartermijn"], ["Wijzigingen eerst in een testomgeving bekijken", "Vier uur voor content of conversieverbeteringen", "Snelheid en analyses beoordelen voor maandprioriteiten", "Dagelijkse back-ups verkorten herstelintervallen"], ["Tien uur voor afgesproken ontwikkeling en koppelingen", "Verzoeken technisch beoordelen en prioriteren op impact", "Prioriteitscontact voor problemen en wijzigingen", "Maandplan binnen goedgekeurde tijd en scope"]],
 de: [["Hosting und SSL überwachen und Probleme melden", "Supportstunde für kleine Inhaltsänderungen oder Fehler", "Monatsübersicht zu Arbeiten und nötigen Entscheidungen", "Wöchentliches Backup gemäß vereinbarter Aufbewahrung"], ["Änderungen vor Veröffentlichung in Testumgebung prüfen", "Vier Stunden für Inhalte oder Conversion-Verbesserungen", "Geschwindigkeit und Analysen für Prioritäten prüfen", "Tägliche Backups verkürzen Wiederherstellungsintervalle"], ["Zehn Stunden für vereinbarte Entwicklung und Anbindungen", "Anfragen nach Wirkung priorisieren und technisch prüfen", "Prioritätskontakt bei Problemen und Änderungen", "Monatsplan innerhalb freigegebener Zeit und Umfang"]],
 tr: [["Hosting ve SSL durumunu izleme ve sorun bildirimi", "Destek saatini küçük içerik veya hata işleri için kullanma", "Yapılan işler ve gereken kararların aylık özeti", "Kararlaştırılan saklama politikasında haftalık yedek"], ["Değişiklikleri yayından önce test ortamında inceleme", "Dört saati içerik veya dönüşüm iyileştirmelerine ayırma", "Hız ve analizlerle aylık öncelik belirleme", "Günlük yedeklerle geri yükleme aralığını azaltma"], ["On saati kararlaştırılan geliştirme ve bağlantılara ayırma", "Talepleri iş etkisine göre teknik olarak değerlendirme", "Sorunlar ve değişiklikler için öncelikli iletişim", "Onaylı süre ve kapsamda aylık iyileştirme planı"]],
 fr: [["Surveiller hébergement et SSL et signaler les anomalies", "Utiliser l’heure de support pour contenus ou petits correctifs", "Bilan mensuel des travaux et décisions nécessaires", "Sauvegarde hebdomadaire selon la rétention convenue"], ["Vérifier les changements en préproduction", "Affecter quatre heures au contenu ou à la conversion", "Examiner vitesse et analyses pour les priorités du mois", "Sauvegardes quotidiennes rapprochant les points de restauration"], ["Affecter dix heures aux développements et intégrations convenus", "Prioriser les demandes par impact avec revue technique", "Communication prioritaire pour incidents et changements", "Plan mensuel dans le temps et le périmètre approuvés"]],
 es: [["Supervisar hosting y SSL y señalar incidencias", "Usar la hora de soporte para contenidos o pequeños arreglos", "Resumen mensual de trabajos y decisiones pendientes", "Copia semanal según la retención acordada"], ["Revisar cambios en pruebas antes de publicar", "Asignar cuatro horas a contenido o mejoras de conversión", "Revisar velocidad y analítica para priorizar el mes", "Copias diarias reducen el intervalo de restauración"], ["Asignar diez horas a desarrollos e integraciones acordados", "Priorizar solicitudes por impacto con revisión técnica", "Comunicación prioritaria para incidencias y cambios", "Plan mensual dentro del tiempo y alcance aprobados"]],
};
