import type {Locale} from "./config";
const rows:Record<Locale,string>={
 ar:"تستخدم بعض صفحات الأدوات والمحتوى العامة Google AdSense. قد تستخدم Google ملفات ارتباط وبيانات تقنية وفق خيارات الموافقة التي يعرضها مزود الإعلانات. لا نرسل بيانات حساب Google أو تقاريرك الخاصة إلى الإعلانات. تحليل نص الرسائل وإنشاء QR يعملان داخل المتصفح. عند استخدام توليد المحتوى بالذكاء الاصطناعي، يُرسل النص الذي تختار إدخاله إلى AI Gateway ومزود النموذج لمعالجته؛ لا تحفظ Blue Sass النص أو الناتج في سجل الاستخدام. قد يحتفظ مزود الخدمة بسجلات وفق سياسته.",
 en:"Some public tools and content pages use Google AdSense. Google may use cookies and technical data according to its consent choices. We do not send Google account data or private reports to advertising. Message analysis and QR generation run in your browser. When using AI generation, the text you enter is sent to AI Gateway and the model provider for processing; Blue Sass usage records do not store the prompt or output. Providers may retain logs under their policies.",
 nl:"Sommige openbare tool- en inhoudspagina’s gebruiken Google AdSense. Google kan cookies en technische gegevens gebruiken volgens uw toestemmingskeuzes. Accountgegevens en privérapporten worden niet voor advertenties verzonden. Berichtenanalyse en QR werken in de browser. Bij AI-generatie wordt uw ingevoerde tekst naar AI Gateway en de modelprovider gestuurd; Blue Sass bewaart prompt en resultaat niet in gebruiksregistraties. Providers kunnen volgens hun beleid logboeken bewaren.",
 de:"Einige öffentliche Tool- und Inhaltsseiten nutzen Google AdSense. Cookies und technische Daten richten sich nach den Einwilligungsoptionen. Kontodaten und private Berichte werden nicht an Werbung übermittelt. Nachrichtenanalyse und QR laufen im Browser. KI-Eingaben werden an AI Gateway und den Modellanbieter gesendet; Blue Sass speichert Eingaben und Ausgaben nicht im Nutzungsprotokoll. Anbieter können eigene Protokolle speichern.",
 tr:"Bazı açık araç ve içerik sayfaları Google AdSense kullanır. Google, onay tercihlerinize göre çerez ve teknik verileri kullanabilir. Hesap verileri ve özel raporlar reklamlara gönderilmez. Mesaj analizi ve QR tarayıcıda çalışır. Yapay zekâ girdileri AI Gateway ve model sağlayıcısına gönderilir; Blue Sass kullanım kayıtlarında metin ve sonuç saklanmaz. Sağlayıcılar kendi politikalarına göre kayıt tutabilir.",
 fr:"Certaines pages publiques utilisent Google AdSense selon les choix de consentement. Les données de compte et rapports privés ne sont pas transmis aux annonces. Analyse de messages et QR fonctionnent dans le navigateur. Les textes saisis pour l’IA sont envoyés à AI Gateway et au fournisseur du modèle; Blue Sass ne conserve pas les textes ou résultats dans le suivi d’usage. Les fournisseurs peuvent conserver des journaux selon leurs politiques.",
 es:"Algunas páginas públicas usan Google AdSense según las opciones de consentimiento. No enviamos datos de cuenta ni informes privados a anuncios. El análisis de mensajes y QR funciona en el navegador. Los textos para IA se envían a AI Gateway y al proveedor; Blue Sass no guarda textos ni resultados en el registro de uso. Los proveedores pueden conservar registros según sus políticas.",
 it:"Alcune pagine pubbliche usano Google AdSense secondo le scelte di consenso. Dati account e rapporti privati non sono inviati agli annunci. Analisi messaggi e QR funzionano nel browser. I testi IA sono inviati ad AI Gateway e al fornitore; Blue Sass non salva testi o risultati nel registro d’uso. I fornitori possono conservare log secondo le loro politiche.",
 pt:"Algumas páginas públicas usam Google AdSense segundo as escolhas de consentimento. Dados de conta e relatórios privados não são enviados para anúncios. Análise de mensagens e QR funcionam no navegador. Textos IA são enviados ao AI Gateway e fornecedor; Blue Sass não guarda textos ou resultados nos registos de uso. Os fornecedores podem guardar logs conforme as suas políticas.",
 pl:"Niektóre publiczne strony korzystają z Google AdSense zgodnie z wyborem zgody. Dane konta i prywatne raporty nie są przesyłane reklamom. Analiza wiadomości i QR działają w przeglądarce. Tekst AI trafia do AI Gateway i dostawcy modelu; Blue Sass nie zapisuje tekstów ani wyników w historii użycia. Dostawcy mogą przechowywać logi zgodnie ze swoimi zasadami.",
 uk:"Деякі публічні сторінки використовують Google AdSense відповідно до вибору згоди. Дані облікового запису та приватні звіти не передаються рекламі. Аналіз повідомлень і QR працюють у браузері. Текст для ШІ передається AI Gateway і постачальнику; Blue Sass не зберігає тексти та результати в обліку використання. Постачальники можуть зберігати журнали за своїми правилами.",
 ru:"Некоторые публичные страницы используют Google AdSense согласно выбору согласия. Данные аккаунта и частные отчёты не передаются рекламе. Анализ сообщений и QR работают в браузере. Текст ИИ отправляется AI Gateway и поставщику; Blue Sass не сохраняет тексты и результаты в учёте использования. Поставщики могут хранить журналы по своим правилам.",
 zh:"部分公共页面按同意选项使用Google AdSense。账号数据和私人报告不会用于广告。消息分析和二维码生成在浏览器中运行。AI输入文本发送至AI Gateway及模型供应商；Blue Sass用量记录不保存输入或输出。供应商可能按其政策保留日志。",
 ja:"一部の公開ページは同意設定に従いGoogle AdSenseを使用します。アカウント情報や非公開レポートは広告に送信しません。メッセージ分析とQR生成はブラウザ内で行います。AI入力はAI Gatewayとモデル提供者に送信され、Blue Sassの利用記録には入力や出力を保存しません。提供者はポリシーに基づきログを保持する場合があります。",
 ko:"일부 공개 페이지는 동의 설정에 따라 Google AdSense를 사용합니다. 계정 정보와 비공개 보고서는 광고에 전송하지 않습니다. 메시지 분석과 QR 생성은 브라우저에서 실행합니다. AI 입력은 AI Gateway와 모델 제공자에게 전송되며 Blue Sass 사용 기록에는 입력과 결과를 저장하지 않습니다. 제공자는 정책에 따라 로그를 보관할 수 있습니다.",
};
export function advertisingPrivacy(locale:Locale){return rows[locale];}
