import { translated } from "./project-builder";
export const billingCopy = {
  saved: translated("تم اعتماد السعر. يمكن للعميل مراجعة العرض واعتماده ثم دفع المرحلة المتاحة.", "Price approved. The client can accept the offer and pay the available stage.", "Prijs goedgekeurd. De klant kan het voorstel accepteren en betalen.", "Preis freigegeben. Der Kunde kann das Angebot annehmen und zahlen.", "Fiyat onaylandı. Müşteri teklifi kabul edip ödeme yapabilir.", "Prix approuvé. Le client peut accepter le devis puis payer.", "Precio aprobado. El cliente puede aceptar y pagar."),
  locked: translated("السعر مقفل بعد حجز الدفع أو بدء التنفيذ أو إلغاء الطلب. راجع حالة المشروع أولًا.", "Price is locked after payment reservation, execution or cancellation. Review the project status.", "Prijs vergrendeld na betaalreservering, uitvoering of annulering.", "Preis nach Zahlungsreservierung, Beginn oder Stornierung gesperrt.", "Ödeme rezervasyonu, başlangıç veya iptalden sonra fiyat kilitli.", "Prix verrouillé après réservation du paiement, démarrage ou annulation.", "Precio bloqueado tras reservar el pago, comenzar o cancelar."),
  invalid: translated("أدخل سعرًا صحيحًا باليورو أكبر من صفر وبحد أقصى منزلتين عشريتين.", "Enter a positive EUR price with at most two decimal places.", "Voer een positieve EUR-prijs in met maximaal twee decimalen.", "Positiven EUR-Preis mit höchstens zwei Dezimalstellen eingeben.", "En fazla iki ondalıklı pozitif EUR fiyatı girin.", "Saisissez un prix EUR positif avec deux décimales maximum.", "Introduce un precio EUR positivo con dos decimales como máximo."),
  title: translated("دفعات المشروع حسب المراحل", "Stage payment schedule", "Betalingen per projectfase", "Zahlungen nach Projektphase", "Proje aşaması ödemeleri", "Paiements par étape", "Pagos por etapa"),
  approval: translated("بانتظار اعتماد السعر النهائي من الإدارة. لا يمكن الدفع قبل الاعتماد.", "Waiting for management to approve the final price. Checkout is unavailable until approval.", "Wacht op goedkeuring van de definitieve prijs. Betalen kan daarna.", "Endpreis wartet auf Freigabe. Zahlung erst nach Freigabe.", "Son fiyat yönetim onayı bekliyor. Onaydan önce ödeme yapılamaz.", "Prix final en attente d’approbation. Paiement après validation.", "Precio final pendiente de aprobación. Pago tras validación."),
  total: translated("السعر النهائي المعتمد", "Approved final price", "Goedgekeurde eindprijs", "Freigegebener Endpreis", "Onaylı son fiyat", "Prix final approuvé", "Precio final aprobado"),
  approve: translated("اعتماد السعر النهائي باليورو", "Approve final price in EUR", "Eindprijs in EUR goedkeuren", "Endpreis in EUR freigeben", "Son fiyatı EUR olarak onayla", "Approuver le prix final en EUR", "Aprobar precio final en EUR"),
  note: translated("تُدفع كل دفعة قبل مرحلتها، بعد إكمال المرحلة السابقة. الاشتراكات ورسوم الجهات الخارجية ليست ضمن هذه الدفعات.", "Each installment is paid before its stage, after the previous stage is complete. Subscriptions and third-party fees are separate.", "Elke termijn vóór de fase, na voltooiing van de vorige. Abonnementen en externe kosten apart.", "Jede Rate vor der Phase, nach Abschluss der vorherigen. Abos und externe Gebühren separat.", "Her taksit aşamadan önce ve önceki aşama bitince ödenir. Abonelik ve dış ücretler ayrıdır.", "Chaque versement précède son étape, après la précédente. Abonnements et frais tiers séparés.", "Cada cuota antes de su etapa, tras completar la anterior. Suscripciones y terceros aparte."),
  waiting: translated("تتاح بعد إكمال المرحلة السابقة", "Available after the previous stage", "Beschikbaar na de vorige fase", "Nach der vorherigen Phase verfügbar", "Önceki aşamadan sonra kullanılabilir", "Disponible après l’étape précédente", "Disponible tras la etapa anterior"),
  preview: translated("تقسيم تقديري؛ يُثبت بعد اعتماد السعر", "Estimated split; fixed after price approval", "Indicatieve verdeling; definitief na prijsgoedkeuring", "Geschätzte Aufteilung; fest nach Preisfreigabe", "Tahmini dağılım; fiyat onayından sonra kesinleşir", "Répartition indicative, fixée après approbation", "Reparto estimado; fijo tras aprobación"),
};
