import { withExtraLocales } from "@/lib/i18n/extra-locales";
import type { Locale } from "./config";
export const deliveryDetails: Record<Locale, string[][]> = withExtraLocales({
 ar: [ ["جلسة لفهم النشاط والجمهور", "توثيق الصفحات والوظائف والأولويات", "اعتماد النطاق والجدول قبل التصميم"], ["رسم رحلات المستخدم والشاشات", "تحديد الخطوط والألوان والمكونات", "نموذج تفاعلي لمراجعته معك"], ["بناء الواجهات ولوحة الإدارة", "ربط البيانات والخدمات المتفق عليها", "مشاركة نسخ تجريبية ومتابعة التقدم"], ["فحص الجوال والمتصفحات والروابط", "اختبار الصلاحيات والنماذج والأداء", "تسجيل الملاحظات وإصلاح الأخطاء"], ["مراجعة المخرجات مع العميل", "اعتماد النسخة وتجهيز الإطلاق", "تسليم الملفات ودليل الاستخدام"] ],
 en: [ ["Discovery of your business and audience", "Document pages, functions and priorities", "Approve scope and schedule before design"], ["Map user journeys and screens", "Define typography, colour and components", "Review an interactive prototype together"], ["Build interfaces and administration", "Connect agreed data and services", "Share previews and progress updates"], ["Check mobile, browsers and links", "Test permissions, forms and performance", "Track issues and verify fixes"], ["Review deliverables with you", "Approve the release and prepare launch", "Hand over files and usage guidance"] ],
 nl: [ ["Uw bedrijf en doelgroep begrijpen", "Pagina’s, functies en prioriteiten vastleggen", "Scope en planning vóór ontwerp goedkeuren"], ["Gebruikersroutes en schermen uitwerken", "Typografie, kleur en componenten bepalen", "Samen een interactief prototype bekijken"], ["Interfaces en beheer bouwen", "Afgesproken data en diensten koppelen", "Voorbeelden en voortgang delen"], ["Mobiel, browsers en links controleren", "Rechten, formulieren en prestaties testen", "Problemen volgen en oplossingen verifiëren"], ["Resultaten samen beoordelen", "Versie goedkeuren en lancering voorbereiden", "Bestanden en handleiding overdragen"] ],
 de: [ ["Geschäft und Zielgruppe verstehen", "Seiten, Funktionen und Prioritäten festlegen", "Umfang und Zeitplan vor Design freigeben"], ["Nutzerwege und Ansichten entwerfen", "Typografie, Farben und Komponenten definieren", "Interaktiven Prototyp gemeinsam prüfen"], ["Oberflächen und Verwaltung entwickeln", "Vereinbarte Daten und Dienste anbinden", "Vorschauen und Fortschritte teilen"], ["Mobilgeräte, Browser und Links prüfen", "Rechte, Formulare und Leistung testen", "Fehler verfolgen und Korrekturen prüfen"], ["Ergebnisse gemeinsam prüfen", "Version freigeben und Start vorbereiten", "Dateien und Anleitung übergeben"] ],
 tr: [ ["İşinizi ve hedef kitlenizi anlama", "Sayfa, işlev ve öncelikleri belgeleme", "Tasarım öncesi kapsam ve takvim onayı"], ["Kullanıcı yolları ve ekranları çizme", "Yazı, renk ve bileşenleri belirleme", "Etkileşimli prototipi birlikte inceleme"], ["Arayüz ve yönetim panelini geliştirme", "Kararlaştırılan veri ve hizmetleri bağlama", "Önizleme ve ilerleme paylaşımı"], ["Mobil, tarayıcı ve bağlantı kontrolü", "Yetki, form ve performans testleri", "Hataları izleme ve düzeltmeleri doğrulama"], ["Çıktıları müşteriyle inceleme", "Sürümü onaylama ve yayına hazırlama", "Dosya ve kullanım kılavuzu teslimi"] ],
 fr: [ ["Comprendre votre activité et votre public", "Documenter pages, fonctions et priorités", "Valider périmètre et calendrier avant design"], ["Dessiner parcours et écrans", "Définir typographie, couleurs et composants", "Examiner ensemble un prototype interactif"], ["Construire interfaces et administration", "Connecter les données et services convenus", "Partager aperçus et avancement"], ["Vérifier mobiles, navigateurs et liens", "Tester droits, formulaires et performances", "Suivre les anomalies et vérifier les corrections"], ["Examiner les livrables ensemble", "Valider la version et préparer le lancement", "Transmettre fichiers et guide d’utilisation"] ],
 es: [ ["Entender su negocio y audiencia", "Documentar páginas, funciones y prioridades", "Aprobar alcance y calendario antes del diseño"], ["Diseñar recorridos y pantallas", "Definir tipografía, colores y componentes", "Revisar juntos un prototipo interactivo"], ["Construir interfaces y administración", "Conectar datos y servicios acordados", "Compartir vistas previas y avances"], ["Comprobar móviles, navegadores y enlaces", "Probar permisos, formularios y rendimiento", "Registrar errores y verificar correcciones"], ["Revisar entregables con el cliente", "Aprobar versión y preparar lanzamiento", "Entregar archivos y guía de uso"] ],
});
