import type { Locale } from "./config";

// Ordered labels shared by the tool directory, metadata, form and report.
const labels: Record<Locale, readonly string[]> = {
  ar: ["أدوات بلو ساس", "فحص نص الرسالة والروابط", "ألصق الرسالة أو الرابط", "فحص الآن", "مسح", "مؤشرات تستحق المراجعة", "لم تظهر المؤشرات المحددة؛ هذا لا يضمن الأمان", "النطاقات الموجودة", "الفحص محلي في متصفحك. لا نرسل النص أو نحفظه، ولا نفتح الروابط.", "يفحص بنية الروابط واختلاف وجهتها وبعض عبارات الاحتيال بالعربية والإنجليزية فقط. لا يتحقق من هوية المرسل أو وجود البريد أو المرفقات أو سمعة الموقع أو SPF/DKIM.", "النص طويل جدًا. الحد 32 KB.", "فحص الموقع", "اختيار تفاصيل المشروع", "رابط غير مشفر HTTP", "بيانات دخول داخل الرابط", "عنوان IP بدل الدومين", "دومين دولي: تحقق من تهجئته؛ ليس دليل احتيال", "وجهة الرابط تختلف عن النص الظاهر", "لغة استعجال أو تهديد بإغلاق الحساب", "طلب كلمة مرور أو رمز تحقق", "مؤشر مرتفع", "تنبيه", "اختر أداة", "لا يوجد رابط HTTP/HTTPS قابل للاستخراج"],
  en: ["Blue Sass Tools", "Message and link text check", "Paste a message or link", "Check now", "Clear", "Indicators to review", "No listed indicators found; safety is not guaranteed", "Domains found", "Analysis stays in your browser. We do not send or save the text or open links.", "Checks link structure, mismatched destinations and some Arabic/English scam phrases only. Does not verify sender identity, mailbox existence, attachments, website reputation or SPF/DKIM.", "Text exceeds the 32 KB limit.", "Website audit", "Project configuration", "Unencrypted HTTP link", "Credentials embedded in link", "IP address instead of domain", "International domain: check spelling; not proof of fraud", "Link destination differs from displayed text", "Urgency or account closure language", "Request for a password or verification code", "High indicator", "Notice", "Choose a tool", "No extractable HTTP/HTTPS links"],
  nl: ["Blue Sass Tools", "Bericht- en linktekst controleren", "Plak een bericht of link", "Controleren", "Wissen", "Signalen om te bekijken", "Geen genoemde signalen; veiligheid niet gegarandeerd", "Gevonden domeinen", "Analyse blijft in uw browser. Tekst wordt niet verzonden of opgeslagen; links worden niet geopend.", "Controleert linkstructuur, afwijkende doelen en enkele Arabische/Engelse fraudezinnen. Geen controle van afzender, mailbox, bijlagen, reputatie of SPF/DKIM.", "Tekst overschrijdt 32 KB.", "Websitecontrole", "Project samenstellen", "Onversleutelde HTTP-link", "Inloggegevens in de link", "IP-adres in plaats van domein", "Internationaal domein: controleer spelling; geen bewijs van fraude", "Doel wijkt af van getoonde tekst", "Urgentie of dreigende accountsluiting", "Verzoek om wachtwoord of verificatiecode", "Hoog signaal", "Let op", "Kies een tool", "Geen herkenbare HTTP/HTTPS-links"],
  de: ["Blue Sass Tools", "Nachrichten und Linktexte prüfen", "Nachricht oder Link einfügen", "Prüfen", "Löschen", "Hinweise prüfen", "Keine aufgeführten Hinweise; Sicherheit nicht garantiert", "Gefundene Domains", "Die Analyse bleibt im Browser. Kein Versand, Speichern oder Öffnen von Links.", "Prüft Linkstruktur, abweichende Ziele und einige arabische/englische Betrugsphrasen. Keine Prüfung von Absender, Postfach, Anhängen, Reputation oder SPF/DKIM.", "Text überschreitet 32 KB.", "Website prüfen", "Projekt konfigurieren", "Unverschlüsselter HTTP-Link", "Zugangsdaten im Link", "IP-Adresse statt Domain", "Internationale Domain: Schreibweise prüfen; kein Betrugsbeweis", "Linkziel weicht vom Text ab", "Dringlichkeit oder Kontosperrung", "Passwort oder Bestätigungscode angefordert", "Hoher Hinweis", "Hinweis", "Tool wählen", "Keine erkennbaren HTTP/HTTPS-Links"],
  tr: ["Blue Sass Araçları", "Mesaj ve bağlantı metni kontrolü", "Mesaj veya bağlantı yapıştırın", "Kontrol et", "Temizle", "İncelenecek işaretler", "Listelenen işaret bulunmadı; güvenlik garantisi değildir", "Bulunan alan adları", "Analiz tarayıcınızda kalır. Metin gönderilmez veya kaydedilmez, bağlantılar açılmaz.", "Bağlantı yapısı, hedef farkları ve bazı Arapça/İngilizce dolandırıcılık ifadeleri incelenir. Gönderen, posta kutusu, ekler, itibar veya SPF/DKIM doğrulanmaz.", "Metin 32 KB sınırını aşıyor.", "Site denetimi", "Proje yapılandırma", "Şifrelenmemiş HTTP bağlantısı", "Bağlantıda giriş bilgileri", "Alan adı yerine IP", "Uluslararası alan adı: yazımı kontrol edin; dolandırıcılık kanıtı değil", "Hedef görünen metinden farklı", "Aciliyet veya hesap kapatma ifadesi", "Parola veya doğrulama kodu talebi", "Yüksek işaret", "Uyarı", "Araç seçin", "HTTP/HTTPS bağlantısı bulunamadı"],
  fr: ["Outils Blue Sass", "Analyse du texte des messages et liens", "Collez un message ou lien", "Analyser", "Effacer", "Indices à examiner", "Aucun indice listé; sécurité non garantie", "Domaines trouvés", "Analyse locale dans votre navigateur. Aucun envoi, stockage ou ouverture de liens.", "Vérifie la structure des liens, les destinations différentes et certaines phrases frauduleuses arabes/anglaises. Ne vérifie pas l’expéditeur, la boîte, les pièces jointes, la réputation ou SPF/DKIM.", "Le texte dépasse 32 Ko.", "Audit de site", "Configurer un projet", "Lien HTTP non chiffré", "Identifiants dans le lien", "Adresse IP au lieu du domaine", "Domaine international: vérifier l’orthographe; pas une preuve de fraude", "Destination différente du texte", "Urgence ou fermeture du compte", "Demande de mot de passe ou code", "Indice élevé", "Attention", "Choisir un outil", "Aucun lien HTTP/HTTPS reconnu"],
  es: ["Herramientas Blue Sass", "Revisión de mensajes y enlaces", "Pega un mensaje o enlace", "Analizar", "Borrar", "Indicios que revisar", "Sin indicios listados; no garantiza seguridad", "Dominios encontrados", "El análisis permanece en tu navegador. No enviamos ni guardamos texto ni abrimos enlaces.", "Revisa estructura, destinos diferentes y algunas frases fraudulentas árabes/inglesas. No verifica remitente, buzón, adjuntos, reputación ni SPF/DKIM.", "El texto supera 32 KB.", "Auditoría web", "Configurar proyecto", "Enlace HTTP sin cifrar", "Credenciales en el enlace", "IP en lugar de dominio", "Dominio internacional: revisa escritura; no prueba fraude", "Destino distinto al texto", "Urgencia o cierre de cuenta", "Petición de contraseña o código", "Indicio alto", "Aviso", "Elige herramienta", "Sin enlaces HTTP/HTTPS reconocibles"],
  it: ["Strumenti Blue Sass", "Controllo messaggi e link", "Incolla messaggio o link", "Controlla", "Cancella", "Indizi da esaminare", "Nessun indizio elencato; sicurezza non garantita", "Domini trovati", "Analisi nel browser. Nessun invio, salvataggio o apertura di link.", "Controlla struttura, destinazioni diverse e alcune frasi arabe/inglesi. Non verifica mittente, casella, allegati, reputazione o SPF/DKIM.", "Testo oltre 32 KB.", "Analisi sito", "Configura progetto", "Link HTTP non cifrato", "Credenziali nel link", "IP invece del dominio", "Dominio internazionale: controlla ortografia; non prova frode", "Destinazione diversa dal testo", "Urgenza o chiusura account", "Richiesta password o codice", "Indizio alto", "Avviso", "Scegli strumento", "Nessun link HTTP/HTTPS riconoscibile"],
  pt: ["Ferramentas Blue Sass", "Verificar mensagens e ligações", "Cole mensagem ou ligação", "Verificar", "Limpar", "Indícios a rever", "Sem indícios listados; segurança não garantida", "Domínios encontrados", "Análise no navegador. Sem envio, armazenamento ou abertura de ligações.", "Verifica estrutura, destinos diferentes e algumas frases árabes/inglesas. Não verifica remetente, caixa de correio, anexos, reputação ou SPF/DKIM.", "Texto acima de 32 KB.", "Auditoria web", "Configurar projeto", "Ligação HTTP não cifrada", "Credenciais na ligação", "IP em vez de domínio", "Domínio internacional: verificar escrita; não prova fraude", "Destino diferente do texto", "Urgência ou encerramento de conta", "Pedido de palavra-passe ou código", "Indício elevado", "Aviso", "Escolher ferramenta", "Sem ligações HTTP/HTTPS reconhecíveis"],
  pl: ["Narzędzia Blue Sass", "Kontrola wiadomości i linków", "Wklej wiadomość lub link", "Sprawdź", "Wyczyść", "Sygnały do sprawdzenia", "Brak wymienionych sygnałów; brak gwarancji bezpieczeństwa", "Znalezione domeny", "Analiza w przeglądarce. Bez wysyłania, zapisywania tekstu i otwierania linków.", "Sprawdza strukturę, różne cele i wybrane arabskie/angielskie zwroty. Nie weryfikuje nadawcy, skrzynki, załączników, reputacji ani SPF/DKIM.", "Tekst przekracza 32 KB.", "Audyt strony", "Konfiguracja projektu", "Nieszyfrowany link HTTP", "Dane logowania w linku", "IP zamiast domeny", "Domena międzynarodowa: sprawdź pisownię; nie dowód oszustwa", "Cel inny niż tekst", "Pilność lub zamknięcie konta", "Prośba o hasło lub kod", "Silny sygnał", "Uwaga", "Wybierz narzędzie", "Brak rozpoznanych linków HTTP/HTTPS"],
  uk: ["Інструменти Blue Sass", "Перевірка повідомлень і посилань", "Вставте повідомлення або посилання", "Перевірити", "Очистити", "Ознаки для перевірки", "Перелічених ознак немає; безпека не гарантована", "Знайдені домени", "Аналіз у браузері. Текст не надсилається й не зберігається, посилання не відкриваються.", "Перевіряє структуру, різні адреси та деякі арабські/англійські фрази. Не перевіряє відправника, скриньку, вкладення, репутацію чи SPF/DKIM.", "Текст перевищує 32 КБ.", "Аудит сайту", "Налаштувати проєкт", "Незашифроване HTTP-посилання", "Облікові дані в посиланні", "IP замість домену", "Міжнародний домен: перевірте написання; не доказ шахрайства", "Адреса відрізняється від тексту", "Терміновість або закриття облікового запису", "Запит пароля або коду", "Сильна ознака", "Увага", "Оберіть інструмент", "Немає розпізнаних HTTP/HTTPS-посилань"],
  ru: ["Инструменты Blue Sass", "Проверка сообщений и ссылок", "Вставьте сообщение или ссылку", "Проверить", "Очистить", "Признаки для проверки", "Перечисленных признаков нет; безопасность не гарантирована", "Найденные домены", "Анализ в браузере. Текст не отправляется и не сохраняется, ссылки не открываются.", "Проверяет структуру, разные адреса и некоторые арабские/английские фразы. Не проверяет отправителя, ящик, вложения, репутацию или SPF/DKIM.", "Текст превышает 32 КБ.", "Аудит сайта", "Настроить проект", "Незашифрованная HTTP-ссылка", "Учётные данные в ссылке", "IP вместо домена", "Международный домен: проверьте написание; не доказательство обмана", "Адрес отличается от текста", "Срочность или закрытие аккаунта", "Запрос пароля или кода", "Сильный признак", "Внимание", "Выберите инструмент", "Нет распознанных HTTP/HTTPS-ссылок"],
  zh: ["Blue Sass 工具", "消息和链接文本检查", "粘贴消息或链接", "检查", "清除", "需检查的迹象", "未发现列出的迹象；不保证安全", "发现的域名", "分析仅在浏览器中进行。不发送或保存文本，不打开链接。", "仅检查链接结构、目标不一致及部分阿拉伯语/英语诈骗措辞。不验证发件人、邮箱、附件、信誉或 SPF/DKIM。", "文本超过32 KB。", "网站审计", "项目配置", "未加密的HTTP链接", "链接包含登录信息", "IP地址而非域名", "国际化域名：检查拼写；不代表诈骗", "目标与显示文本不同", "紧急或关闭账号措辞", "索取密码或验证码", "高风险迹象", "提示", "选择工具", "无可识别的HTTP/HTTPS链接"],
  ja: ["Blue Sass ツール", "メッセージとリンクの確認", "メッセージかリンクを貼り付け", "確認", "消去", "確認すべき兆候", "該当する兆候なし。安全を保証しません", "検出されたドメイン", "ブラウザ内で分析します。送信・保存やリンクの閲覧はしません。", "リンク構造、宛先の相違、一部のアラビア語・英語表現のみ確認します。送信者、メールボックス、添付、評判、SPF/DKIMは検証しません。", "32 KBを超えています。", "サイト監査", "プロジェクト設定", "暗号化されていないHTTPリンク", "リンク内の認証情報", "ドメインではなくIPアドレス", "国際化ドメイン：綴りを確認。詐欺の証拠ではありません", "宛先が表示テキストと異なる", "緊急やアカウント閉鎖の表現", "パスワードや認証コードの要求", "強い兆候", "注意", "ツールを選択", "認識可能なHTTP/HTTPSリンクなし"],
  ko: ["Blue Sass 도구", "메시지 및 링크 텍스트 검사", "메시지 또는 링크 붙여넣기", "검사", "지우기", "검토할 징후", "나열된 징후 없음. 안전을 보장하지 않습니다", "발견된 도메인", "브라우저에서만 분석합니다. 텍스트를 전송·저장하거나 링크를 열지 않습니다.", "링크 구조, 대상 불일치 및 일부 아랍어·영어 문구만 검사합니다. 발신자, 메일함, 첨부파일, 평판 또는 SPF/DKIM은 검증하지 않습니다.", "32 KB를 초과했습니다.", "웹사이트 감사", "프로젝트 구성", "암호화되지 않은 HTTP 링크", "링크에 로그인 정보 포함", "도메인 대신 IP 주소", "국제 도메인: 철자 확인. 사기의 증거는 아님", "대상이 표시 텍스트와 다름", "긴급 또는 계정 폐쇄 문구", "비밀번호 또는 인증 코드 요청", "높은 징후", "알림", "도구 선택", "인식 가능한 HTTP/HTTPS 링크 없음"],
};
export function messageToolCopy(locale: Locale) {
  const [tools, title, input, scan, clear, found, none, domains, privacy, limits, error, audit, quote, insecure_link, embedded_credentials, ip_address, international_domain, hidden_destination, urgent_language, secret_request, high, warning, choose, noLinks] = labels[locale];
  return { tools, title, input, scan, clear, found, none, domains, privacy, limits, error, audit, quote, high, warning, choose, noLinks, findings: { insecure_link, embedded_credentials, ip_address, international_domain, hidden_destination, urgent_language, secret_request } };
}
