import type { Locale } from "./config";

type PaymentCopy = {
  title: string;
  subtitle: string;
  back: string;
  summary: string;
  project: string;
  amount: string;
  method: string;
  paypal: string;
  secure: string;
  sandbox: string;
  pay: string;
  paid: string;
  pending: string;
  failed: string;
  retry: string;
  cancelled: string;
  cancelledNote: string;
  success: string;
  error: string;
  unavailable: string;
  processing: string;
};

export const paymentCopy: Record<Locale, PaymentCopy> = {
  ar: { title: "الدفع الآمن", subtitle: "أكمل دفعة مشروعك عبر PayPal. لا نخزن بيانات حسابك أو بطاقتك.", back: "العودة إلى المشروع", summary: "ملخص الدفع", project: "المشروع", amount: "المبلغ", method: "طريقة الدفع", paypal: "PayPal Checkout", secure: "يُنشأ الطلب ويُؤكد من خادم Blue Sass، ولا يُعتمد الدفع إلا بعد تأكيد PayPal اكتماله.", sandbox: "وضع Sandbox التجريبي", pay: "الدفع عبر PayPal", paid: "مدفوع", pending: "بانتظار التأكيد", failed: "لم يكتمل الدفع", retry: "إعادة المحاولة", cancelled: "أُلغيت عملية الدفع", cancelledNote: "لم يتم خصم أي مبلغ. يمكنك المحاولة مجددًا عندما تكون جاهزًا.", success: "تم تأكيد الدفع بنجاح.", error: "تعذر إتمام الدفع. لم نعتمد المشروع كمدفوع؛ حاول مجددًا أو تواصل معنا.", unavailable: "الدفع عبر PayPal غير متاح حاليًا. يرجى التواصل معنا.", processing: "جارٍ التحقق من PayPal…" },
  en: { title: "Secure payment", subtitle: "Complete your project payment with PayPal. We never store your PayPal or card details.", back: "Back to project", summary: "Payment summary", project: "Project", amount: "Amount", method: "Payment method", paypal: "PayPal Checkout", secure: "The order is created and verified by the Blue Sass server. Payment is accepted only after PayPal confirms completion.", sandbox: "Sandbox test mode", pay: "Pay with PayPal", paid: "Paid", pending: "Awaiting confirmation", failed: "Payment not completed", retry: "Try again", cancelled: "Payment cancelled", cancelledNote: "No payment was recorded. You can try again whenever you are ready.", success: "Your payment was confirmed successfully.", error: "Payment could not be completed. We did not mark the project as paid; please retry or contact us.", unavailable: "PayPal payment is currently unavailable. Please contact us.", processing: "Confirming with PayPal…" },
  nl: { title: "Veilig betalen", subtitle: "Betaal uw project veilig met PayPal. Wij bewaren geen PayPal- of kaartgegevens.", back: "Terug naar project", summary: "Betalingsoverzicht", project: "Project", amount: "Bedrag", method: "Betaalmethode", paypal: "PayPal Checkout", secure: "De bestelling wordt door de Blue Sass-server gemaakt en gecontroleerd. Alleen een PayPal-bevestiging met voltooide status geldt als betaling.", sandbox: "Sandbox-testmodus", pay: "Betalen met PayPal", paid: "Betaald", pending: "Wacht op bevestiging", failed: "Betaling niet voltooid", retry: "Opnieuw proberen", cancelled: "Betaling geannuleerd", cancelledNote: "Er is geen betaling geregistreerd. U kunt het later opnieuw proberen.", success: "Uw betaling is bevestigd.", error: "De betaling kon niet worden voltooid. Het project is niet als betaald gemarkeerd; probeer opnieuw of neem contact op.", unavailable: "PayPal-betaling is momenteel niet beschikbaar. Neem contact met ons op.", processing: "Bevestigen bij PayPal…" },
  de: { title: "Sichere Zahlung", subtitle: "Bezahlen Sie Ihr Projekt sicher mit PayPal. Wir speichern keine PayPal- oder Kartendaten.", back: "Zurück zum Projekt", summary: "Zahlungsübersicht", project: "Projekt", amount: "Betrag", method: "Zahlungsart", paypal: "PayPal Checkout", secure: "Die Bestellung wird vom Blue-Sass-Server erstellt und geprüft. Eine Zahlung gilt erst nach PayPal-Bestätigung als abgeschlossen.", sandbox: "Sandbox-Testmodus", pay: "Mit PayPal zahlen", paid: "Bezahlt", pending: "Bestätigung ausstehend", failed: "Zahlung nicht abgeschlossen", retry: "Erneut versuchen", cancelled: "Zahlung abgebrochen", cancelledNote: "Es wurde keine Zahlung erfasst. Sie können es jederzeit erneut versuchen.", success: "Ihre Zahlung wurde erfolgreich bestätigt.", error: "Die Zahlung konnte nicht abgeschlossen werden. Das Projekt wurde nicht als bezahlt markiert; versuchen Sie es erneut oder kontaktieren Sie uns.", unavailable: "PayPal-Zahlung ist derzeit nicht verfügbar. Bitte kontaktieren Sie uns.", processing: "Bestätigung durch PayPal…" },
  tr: { title: "Güvenli ödeme", subtitle: "Proje ödemenizi PayPal ile güvenle tamamlayın. PayPal veya kart bilgilerinizi saklamayız.", back: "Projeye dön", summary: "Ödeme özeti", project: "Proje", amount: "Tutar", method: "Ödeme yöntemi", paypal: "PayPal Checkout", secure: "Sipariş Blue Sass sunucusunda oluşturulur ve doğrulanır. PayPal işlemi tamamlandı olarak onaylamadan ödeme kabul edilmez.", sandbox: "Sandbox test modu", pay: "PayPal ile öde", paid: "Ödendi", pending: "Onay bekleniyor", failed: "Ödeme tamamlanmadı", retry: "Tekrar dene", cancelled: "Ödeme iptal edildi", cancelledNote: "Herhangi bir ödeme kaydedilmedi. Hazır olduğunuzda tekrar deneyebilirsiniz.", success: "Ödemeniz başarıyla onaylandı.", error: "Ödeme tamamlanamadı. Proje ödenmiş sayılmadı; tekrar deneyin veya bizimle iletişime geçin.", unavailable: "PayPal ödemesi şu anda kullanılamıyor. Lütfen bize ulaşın.", processing: "PayPal ile doğrulanıyor…" },
  fr: { title: "Paiement sécurisé", subtitle: "Réglez votre projet avec PayPal. Nous ne conservons aucune donnée PayPal ou bancaire.", back: "Retour au projet", summary: "Récapitulatif", project: "Projet", amount: "Montant", method: "Mode de paiement", paypal: "PayPal Checkout", secure: "La commande est créée et vérifiée par le serveur Blue Sass. Le paiement n’est accepté qu’après confirmation de son achèvement par PayPal.", sandbox: "Mode test Sandbox", pay: "Payer avec PayPal", paid: "Payé", pending: "Confirmation en attente", failed: "Paiement non finalisé", retry: "Réessayer", cancelled: "Paiement annulé", cancelledNote: "Aucun paiement n’a été enregistré. Vous pourrez réessayer quand vous le souhaitez.", success: "Votre paiement a été confirmé.", error: "Le paiement n’a pas pu aboutir. Le projet n’est pas marqué comme payé ; réessayez ou contactez-nous.", unavailable: "Le paiement PayPal est momentanément indisponible. Contactez-nous.", processing: "Confirmation auprès de PayPal…" },
  es: { title: "Pago seguro", subtitle: "Complete el pago del proyecto con PayPal. No guardamos datos de PayPal ni de tarjetas.", back: "Volver al proyecto", summary: "Resumen del pago", project: "Proyecto", amount: "Importe", method: "Método de pago", paypal: "PayPal Checkout", secure: "El pedido se crea y verifica en el servidor de Blue Sass. Solo se acepta el pago cuando PayPal confirma que está completado.", sandbox: "Modo de prueba Sandbox", pay: "Pagar con PayPal", paid: "Pagado", pending: "Pendiente de confirmación", failed: "Pago no completado", retry: "Volver a intentar", cancelled: "Pago cancelado", cancelledNote: "No se registró ningún pago. Puede volver a intentarlo cuando quiera.", success: "El pago se confirmó correctamente.", error: "No se pudo completar el pago. El proyecto no se marcó como pagado; inténtelo de nuevo o contáctenos.", unavailable: "El pago con PayPal no está disponible ahora. Contáctenos.", processing: "Confirmando con PayPal…" },
};
