import { withExtraLocales } from "./extra-locales";
import type { Locale } from "./config";
import nl from "./tools-base/nl.json";
import de from "./tools-base/de.json";
import tr from "./tools-base/tr.json";
import fr from "./tools-base/fr.json";
import es from "./tools-base/es.json";
export const toolEnglish = {
  team: "Team and permissions", owner: "Platform owner", permissions: "Permissions", permissionHelp: "Roles do not automatically grant access. Only the owner can invite, change permissions or suspend accounts. Unselected permissions are denied.",
  accounts: "Accounts", email: "Email", invite: "Send staff invitation", invitations: "Invitations", save: "Save permissions", enabled: "Active", disabled: "Suspended", deactivate: "Suspend account", reactivate: "Restore account", confirm: "I confirm this account change", revoke: "Revoke invitation", auditLog: "Activity log", empty: "Nothing here yet", protected: "The owner account cannot be suspended or changed here.",
  assignment: "Assign project access", project: "Project", member: "Staff member", assign: "Assign", remove: "Remove assignment", accept: "Accept invitation", inviteHelp: "Sign in with the invited email, then reopen your invitation link. Invitations expire after seven days.", admin: "Administration",
  audit: "Website and source review", auditIntro: "Run an automated review of a public page or your source files, then receive measured findings and practical next steps.", url: "Public website URL", sourceUrl: "Website link", sourceFiles: "Source files", name: "Project name", files: "Select files", folder: "Select folder", uploadLimits: "Source files only: up to 500 files, 3 MB total and 500 KB per file. Exclude .env, keys, dependencies and build folders. Archives and executable files are not supported.", consent: "I own this website or these files, or have permission to review them.", privacy: "Uploaded source is analysed in memory, never executed, and not sent to an AI provider. Only findings and file names are saved privately in your account; raw source and matched secret values are not retained.", pending: "Uploading and analysing. Please keep this page open.", currentPlan: "Current access", available: "Reviews in this period", maxSites: "Projects or website targets", history: "Report history", run: "Run review", report: "Review report", print: "Print or save PDF", exportJson: "Export JSON", compare: "Compare with a previous report", passed: "Passed check", warning: "Needs review", notTested: "Not tested", more: "Show more findings", free: "One complete initial review is available free each calendar month after sign-in.",
  limits: "This is a bounded automated review, not penetration testing, a full vulnerability audit or an accessibility certification. A website review reads one public page and samples up to three same-origin links. Fetch time is measured from our server, not a real user's browser. Source review uses static indicators and does not install dependencies, execute code or inspect a private database. Findings can be false positives.",
  plansTitle: "Useful tools for your digital projects", plansIntro: "Choose automated reviews and reports, not a bundle of staff working hours.", planNote: "Access lasts 30 days after confirmed live payment. Renewal is manual; no automatic charge. Scheduled monitoring, staff development, automatic fixes and backups are not included in these new tool plans. Existing subscription agreements remain unchanged.", hostingNote: "Existing paid hosting access remains subject to the current upload and deployment limits. These plans do not increase hosting capacity.", reportLimit: "{count} automated reviews per 30-day period", siteLimit: "{count} project or website targets", toolFeatures: ["Public-page and source-file review", "Clear findings and suggested next steps", "Private report history", "Print complete reports or save as PDF"], comparisonFeature: "Compare findings before and after a change", jsonFeature: "Structured JSON export for your own workflow", buy: "Buy access", previous: "Previous report", selected: "Selected files", ignored: "Excluded files", requestImprovement: "Request an improvement quote", unavailable: "Sign in to run and save your review.",
  categories: { security: "Security indicators", seo: "Search visibility", accessibility: "Accessibility indicators", performance: "Page transfer measurements", links: "Link sample", source: "Source checks" },
  capabilities: {
    "leads.read": "Read pricing requests", "leads.manage": "Manage pricing requests", "projects.read_assigned": "Open administration for assigned projects", "projects.read_all": "Read all projects", "projects.edit_all": "Edit all projects", "projects.edit_assigned": "Edit assigned projects only", "projects.assign": "Assign staff to visible projects", "projects.stage": "Change stages of visible projects", "billing.approve": "Approve final prices of visible projects", "portfolio.manage": "Manage portfolio for visible projects", "reviews.manage": "Moderate customer reviews", "announcements.send": "Send offers to opted-in users", "cms.manage": "Manage site statistics",
  },
  errors: {
    SAVED: "Changes saved.", INVITATION_SENT: "Invitation sent. Access starts only after the recipient accepts it.", OWNER_PROTECTED: "The owner account is protected.", READ_ONLY_ACCOUNT: "This account is restricted to read-only access.", DELIVERY_UNAVAILABLE: "The invitation could not be delivered. No working invitation link is exposed here.", INVITATION_INVALID: "The invitation is invalid, expired, revoked, already used, or belongs to another email.",
    INVALID_INPUT: "Check the input and try again.", UNAUTHORISED: "Sign in with an authorised account.", CONSENT_REQUIRED: "Confirm you are authorised to review this website or these files.", UNAVAILABLE: "Reviews are temporarily unavailable.", URL_BLOCKED: "Use a public domain with HTTP or HTTPS. Private addresses, custom ports and credentials are not accepted.", URL_UNAVAILABLE: "The page could not be reached within the review limits. No completed report credit was consumed.", HTML_REQUIRED: "This review requires a public HTML page.", FILE_BLOCKED: "One or more files are unsupported, private configuration files, binary files or too large.", UPLOAD_LIMIT: "The source upload exceeds the allowed size or file count.", AUDIT_BUSY: "A review is already running, or too many requests were submitted. Please try later.", AUDIT_QUOTA: "Your review allowance for this period is used. Choose a plan or wait for the next period.", SITE_QUOTA: "Your target allowance is used. Review an existing target or choose a larger plan.",
  },
  rules: {
    title: "Page title", description: "Meta description", canonical: "Canonical link", heading: "Main heading", html_language: "Declared page language", viewport: "Mobile viewport", image_alt: "Images without an alt attribute", insecure_resources: "HTTP resource references", visual_browser: "Real-browser performance and visual testing", full_accessibility: "Full accessibility audit", secret_indicators: "Possible hard-coded secret indicators", dynamic_execution: "Dynamic code execution requires review", html_injection_review: "Raw HTML insertion requires review", tls_disabled: "TLS certificate checks disabled in source", files_read: "Source files inspected", runtime_database: "Private database, running code and full security testing", dependencies_database: "Dependency vulnerability database comparison", http_status: "Page response status", https: "HTTPS on the reviewed page", csp: "Content Security Policy header present", hsts: "Strict Transport Security header", nosniff: "Content type protection header", referrer: "Referrer policy header", framing: "Framing restrictions", html_fetch_ms: "HTML fetch time from our server in milliseconds", html_bytes: "HTML transfer size in bytes", sample_links: "Unsuccessful requests in the sampled links", full_crawl: "Complete website crawl",
  },
  recommendations: {
    title: "Add a meaningful page title in the document head or framework metadata.", description: "Add a page-specific meta description; this check does not evaluate its quality.", canonical: "Check whether a canonical URL is appropriate and configure it for this page.", heading: "Provide a clear main heading that explains the page.", html_language: "Declare the correct language on the HTML element.", viewport: "Configure a mobile viewport and verify the actual layout on small screens.", image_alt: "Add appropriate alt attributes. Decorative images can use an empty alt attribute.", insecure_resources: "Review HTTP references and use HTTPS where possible.", secret_indicators: "Manually verify the indicator. If it is a real credential, remove it from source and history and rotate it with the provider. No matched value is included in this report.", dynamic_execution: "Review whether untrusted input can reach dynamic execution. Use safer alternatives or isolate execution.", html_injection_review: "Verify escaping or sanitisation of any untrusted data inserted as HTML.", tls_disabled: "Enable certificate validation and fix certificate problems instead of bypassing checks.", http_status: "Check the response status. An error or access challenge may prevent review of the real page.", https: "Configure a valid HTTPS certificate and redirect public HTTP traffic appropriately.", csp: "Consider a Content Security Policy compatible with the site. Header presence alone is not a full policy assessment.", hsts: "Review HTTPS readiness before enabling a suitable HSTS policy.", nosniff: "Use a valid X-Content-Type-Options: nosniff header.", referrer: "Review referrer exposure and choose an appropriate restrictive policy.", framing: "Set framing restrictions appropriate for any legitimate embedding requirements.", sample_links: "Review sampled requests manually. HEAD limitations, access controls and timeouts do not always mean a broken link.",
  },
  events: { "permissions.updated": "Permissions changed", "account.enabled": "Account restored", "account.disabled": "Account suspended", "invitation.sent": "Invitation sent", "invitation.revoked": "Invitation revoked", "invitation.accepted": "Invitation accepted", "project.assigned": "Project assigned", "project.unassigned": "Assignment removed", "price.approved": "Final price approved", "stage.updated": "Project stage changed" },
};
const toolArabic: typeof toolEnglish = {
  team: "الموظفون والصلاحيات", owner: "مالك المنصة", permissions: "الصلاحيات", permissionHelp: "اسم الدور لا يمنح صلاحيات تلقائيًا. المالك وحده يرسل الدعوات ويعدل الصلاحيات ويوقف الحسابات. أي صلاحية غير محددة تُرفض.",
  accounts: "الحسابات", email: "البريد الإلكتروني", invite: "إرسال دعوة موظف", invitations: "الدعوات", save: "حفظ الصلاحيات", enabled: "نشط", disabled: "موقوف", deactivate: "إيقاف الحساب", reactivate: "إعادة تفعيل الحساب", confirm: "أؤكد تغيير حالة هذا الحساب", revoke: "إلغاء الدعوة", auditLog: "سجل التغييرات", empty: "لا توجد بيانات بعد", protected: "لا يمكن إيقاف حساب المالك أو تعديل ملكيته من هنا.",
  assignment: "إسناد الوصول للمشروع", project: "المشروع", member: "الموظف", assign: "إسناد", remove: "إزالة الإسناد", accept: "قبول الدعوة", inviteHelp: "سجّل الدخول بالبريد المدعو، ثم افتح رابط الدعوة مرة أخرى. تنتهي صلاحية الدعوة بعد سبعة أيام.", admin: "لوحة الإدارة",
  audit: "فحص الموقع وملفات المشروع", auditIntro: "افحص صفحة منشورة أو ملفات المصدر آليًا، واحصل على نتائج فعلية وخطوات واضحة للمراجعة والتحسين.", url: "رابط الموقع المنشور", sourceUrl: "رابط الموقع", sourceFiles: "ملفات المصدر", name: "اسم المشروع", files: "اختيار ملفات", folder: "اختيار فولدر", uploadLimits: "ملفات المصدر فقط: حتى 500 ملف، بإجمالي 3 MB، وحتى 500 KB للملف. استبعد .env والمفاتيح والاعتماديات ومجلدات البناء. لا ندعم الأرشيف أو الملفات التنفيذية.", consent: "أملك هذا الموقع أو الملفات، أو لدي إذن بفحصها.", privacy: "نحلّل المصدر مؤقتًا في الذاكرة دون تشغيله أو إرساله لخدمة ذكاء اصطناعي. نحفظ النتائج وأسماء الملفات بشكل خاص في حسابك فقط، ولا نحتفظ بالمصدر أو القيم السرية المكتشفة.", pending: "جارٍ الرفع والتحليل. اترك الصفحة مفتوحة حتى تظهر النتيجة.", currentPlan: "الوصول الحالي", available: "عدد الفحوص في هذه الفترة", maxSites: "المشاريع أو المواقع", history: "سجل التقارير", run: "ابدأ الفحص", report: "تقرير الفحص", print: "طباعة أو حفظ PDF", exportJson: "تصدير JSON", compare: "مقارنة بتقرير سابق", passed: "اجتاز الفحص المحدد", warning: "يحتاج مراجعة", notTested: "لم يُفحص", more: "عرض نتائج إضافية", free: "فحص أولي كامل واحد مجانًا كل شهر تقويمي بعد تسجيل الدخول.",
  limits: "هذا فحص آلي محدود، وليس اختبار اختراق أو تدقيقًا شاملًا للثغرات أو شهادة لإمكانية الوصول. نفحص صفحة منشورة وعينة حتى ثلاثة روابط داخل نفس الموقع. زمن الجلب يُقاس من خادمنا، وليس متصفح الزائر. فحص المصدر يبحث عن مؤشرات ثابتة دون تثبيت الاعتماديات أو تشغيل الكود أو الوصول لقاعدة بيانات خاصة. قد تتطلب بعض النتائج التحقق اليدوي.",
  plansTitle: "أدوات يحتاجها مشروعك الرقمي", plansIntro: "اختر فحوصًا وتقارير آلية مفيدة، بدل باقات ساعات عمل للفريق.", planNote: "يستمر الوصول 30 يومًا بعد تأكيد الدفع الحقيقي. التجديد يدوي ولا يوجد خصم تلقائي. الباقات الجديدة لا تشمل مراقبة مجدولة أو تطويرًا من الفريق أو إصلاحًا آليًا أو نسخًا احتياطيًا. تبقى اتفاقيات الاشتراكات السابقة كما هي.", hostingNote: "يبقى وصول الاستضافة المدفوع خاضعًا لحدود الرفع والنشر الحالية. هذه الباقات لا تزيد سعة الاستضافة.", reportLimit: "{count} فحص آلي لكل فترة 30 يومًا", siteLimit: "{count} مشروع أو موقع", toolFeatures: ["فحص الصفحة المنشورة وملفات المصدر", "نتائج واضحة وخطوات للمراجعة والتحسين", "سجل تقارير خاص بحسابك", "طباعة التقارير الكاملة أو حفظها PDF"], comparisonFeature: "مقارنة النتائج قبل التعديل وبعده", jsonFeature: "تصدير JSON منظّم للاستخدام في أدواتك", buy: "اشترِ الوصول", previous: "التقرير السابق", selected: "الملفات المحددة", ignored: "الملفات المستبعدة", requestImprovement: "طلب عرض سعر للتحسين", unavailable: "سجّل الدخول لإجراء الفحص وحفظ تقريرك.",
  categories: { security: "مؤشرات الحماية", seo: "الظهور في البحث", accessibility: "مؤشرات إمكانية الوصول", performance: "قياسات نقل الصفحة", links: "عينة الروابط", source: "فحوص المصدر" },
  capabilities: { "leads.read": "قراءة طلبات التسعير", "leads.manage": "إدارة طلبات التسعير", "projects.read_assigned": "دخول الإدارة للمشاريع المسندة", "projects.read_all": "قراءة جميع المشاريع", "projects.edit_all": "تعديل جميع المشاريع", "projects.edit_assigned": "تعديل المشاريع المسندة فقط", "projects.assign": "إسناد موظفين للمشاريع المتاحة له", "projects.stage": "تغيير مراحل المشاريع المتاحة له", "billing.approve": "اعتماد أسعار المشاريع المتاحة له", "portfolio.manage": "إدارة عرض الأعمال للمشاريع المتاحة له", "reviews.manage": "مراجعة آراء العملاء", "announcements.send": "إرسال عروض للمستخدمين الموافقين", "cms.manage": "إدارة إحصاءات الموقع" },
  errors: { SAVED: "تم حفظ التغييرات.", INVITATION_SENT: "أُرسلت الدعوة. لا يبدأ الوصول قبل قبول الموظف لها.", OWNER_PROTECTED: "حساب المالك محمي.", READ_ONLY_ACCOUNT: "هذا الحساب مخصص للقراءة فقط.", DELIVERY_UNAVAILABLE: "تعذّر تسليم الدعوة. لا نعرض هنا رابط دعوة صالحًا.", INVITATION_INVALID: "الدعوة غير صالحة أو منتهية أو ملغاة أو مستخدمة، أو تخص بريدًا آخر.", INVALID_INPUT: "تحقق من البيانات ثم أعد المحاولة.", UNAUTHORISED: "سجّل الدخول بحساب مخوّل.", CONSENT_REQUIRED: "أكد أن لديك إذنًا بفحص هذا الموقع أو الملفات.", UNAVAILABLE: "الفحص غير متاح مؤقتًا.", URL_BLOCKED: "استخدم نطاقًا عامًا عبر HTTP أو HTTPS، دون عناوين داخلية أو منافذ مخصصة أو بيانات دخول.", URL_UNAVAILABLE: "تعذّر الوصول للصفحة ضمن حدود الفحص. لم تُستهلك حصة تقرير مكتمل.", HTML_REQUIRED: "هذا الفحص يحتاج صفحة HTML منشورة.", FILE_BLOCKED: "هناك ملفات غير مدعومة أو ملفات إعدادات خاصة أو ملفات ثنائية أو كبيرة جدًا.", UPLOAD_LIMIT: "تجاوزت ملفات المصدر الحجم أو العدد المسموح.", AUDIT_BUSY: "هناك فحص قيد التنفيذ أو طلبات كثيرة. حاول لاحقًا.", AUDIT_QUOTA: "استُهلكت حصة الفحص لهذه الفترة. اختر باقة أو انتظر الفترة التالية.", SITE_QUOTA: "استُهلك عدد المشاريع المتاح. افحص مشروعًا سابقًا أو اختر باقة أكبر." },
  rules: { title: "عنوان الصفحة", description: "وصف الصفحة لمحركات البحث", canonical: "رابط الصفحة الأساسي", heading: "العنوان الرئيسي", html_language: "لغة الصفحة المعلنة", viewport: "إعداد عرض الجوال", image_alt: "صور دون خاصية النص البديل", insecure_resources: "مراجع موارد تستخدم HTTP", visual_browser: "الأداء والفحص البصري في متصفح فعلي", full_accessibility: "تدقيق كامل لإمكانية الوصول", secret_indicators: "مؤشرات قيم سرية مكتوبة داخل الكود", dynamic_execution: "تشغيل كود ديناميكي يحتاج مراجعة", html_injection_review: "إدخال HTML خام يحتاج مراجعة", tls_disabled: "تعطيل التحقق من شهادات TLS في المصدر", files_read: "ملفات المصدر التي فُحصت", runtime_database: "قاعدة البيانات وتشغيل الكود والفحص الأمني الشامل", dependencies_database: "مقارنة الاعتماديات بقاعدة ثغرات", http_status: "حالة استجابة الصفحة", https: "استخدام HTTPS في الصفحة المفحوصة", csp: "وجود ترويسة سياسة أمان المحتوى", hsts: "ترويسة فرض الاتصال الآمن", nosniff: "ترويسة حماية نوع المحتوى", referrer: "ترويسة سياسة الإحالة", framing: "قيود تضمين الصفحة", html_fetch_ms: "زمن جلب HTML من خادمنا بالملّي ثانية", html_bytes: "حجم HTML المنقول بالبايت", sample_links: "طلبات غير ناجحة في عينة الروابط", full_crawl: "زحف شامل لجميع صفحات الموقع" },
  recommendations: { title: "أضف عنوانًا واضحًا في رأس الصفحة أو إعدادات metadata في إطار العمل.", description: "أضف وصفًا خاصًا بالصفحة. هذا الفحص لا يقيّم جودة الوصف.", canonical: "راجع الحاجة للرابط الأساسي واضبطه بما يناسب هذه الصفحة.", heading: "ضع عنوانًا رئيسيًا يشرح محتوى الصفحة بوضوح.", html_language: "حدد لغة HTML الصحيحة.", viewport: "اضبط إعداد عرض الجوال ثم افحص التصميم فعليًا على الشاشات الصغيرة.", image_alt: "أضف خاصية alt المناسبة. يمكن للصور الزخرفية استخدام نص بديل فارغ.", insecure_resources: "راجع المراجع التي تستخدم HTTP واستخدم HTTPS حيث يمكن.", secret_indicators: "تحقق يدويًا من المؤشر. إن كانت بيانات دخول حقيقية، احذفها من المصدر والتاريخ وغيّرها لدى المزود. التقرير لا يعرض القيمة المكتشفة.", dynamic_execution: "راجع وصول البيانات غير الموثوقة إلى تشغيل الكود الديناميكي. استخدم بديلًا أكثر أمانًا أو اعزل التنفيذ.", html_injection_review: "تحقق من تنظيف أو ترميز البيانات غير الموثوقة التي تُدرج كـ HTML.", tls_disabled: "فعّل التحقق من الشهادات وأصلح مشكلتها بدل تجاوزها.", http_status: "راجع حالة الاستجابة. قد تمنع صفحة خطأ أو حماية آلية فحص الصفحة المطلوبة.", https: "اضبط شهادة HTTPS صالحة والتحويل المناسب من HTTP.", csp: "راجع إضافة سياسة CSP متوافقة مع الموقع. وجود الترويسة وحده ليس تقييمًا شاملًا للسياسة.", hsts: "تأكد من جاهزية HTTPS قبل تفعيل سياسة HSTS المناسبة.", nosniff: "استخدم ترويسة X-Content-Type-Options بقيمة nosniff الصحيحة.", referrer: "راجع المعلومات المرسلة مع الإحالة واختر سياسة مقيّدة مناسبة.", framing: "اضبط قيود تضمين الموقع بما يتوافق مع أي تضمين مشروع تحتاجه.", sample_links: "راجع عينة الروابط يدويًا. منع HEAD أو التحكم بالوصول أو انتهاء المهلة لا يعني دائمًا أن الرابط معطل." },
  events: { "permissions.updated": "تعديل الصلاحيات", "account.enabled": "إعادة تفعيل الحساب", "account.disabled": "إيقاف الحساب", "invitation.sent": "إرسال دعوة", "invitation.revoked": "إلغاء دعوة", "invitation.accepted": "قبول دعوة", "project.assigned": "إسناد مشروع", "project.unassigned": "إزالة إسناد", "price.approved": "اعتماد السعر النهائي", "stage.updated": "تغيير مرحلة المشروع" },
};
const baseLexicons: Record<string, Record<string, string>> = { nl, de, tr, fr, es };
function baseCopy<T>(value: T, locale: string): T {
  if (typeof value === "string") return (baseLexicons[locale][value] ?? value) as T;
  if (Array.isArray(value)) return value.map(item => baseCopy(item, locale)) as T;
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, baseCopy(item, locale)])) as T;
  return value;
}
const copies = withExtraLocales({ en: toolEnglish, ar: toolArabic, nl: baseCopy(toolEnglish, "nl"), de: baseCopy(toolEnglish, "de"), tr: baseCopy(toolEnglish, "tr"), fr: baseCopy(toolEnglish, "fr"), es: baseCopy(toolEnglish, "es") });
const periods: Record<Locale, string> = { ar: "30 يومًا", en: "30 days", nl: "30 dagen", de: "30 Tage", tr: "30 gün", fr: "30 jours", es: "30 días", it: "30 giorni", pt: "30 dias", pl: "30 dni", uk: "30 днів", ru: "30 дней", zh: "30天", ja: "30日", ko: "30일" };
export function platformCopy(locale: Locale) { return { ...copies[locale], period: periods[locale] }; }
