import { locales, type Locale } from "./config";

export function translated(...values: [string, string, string, string, string, string, string]): Record<Locale, string> {
  return Object.fromEntries(locales.map((locale, i) => [locale, values[i]])) as Record<Locale, string>;
}

export const builderCopy = {
  next: translated("التالي", "Next", "Volgende", "Weiter", "İleri", "Suivant", "Siguiente"),
  domain: translated("النطاق المطلوب", "Preferred domain", "Gewenst domein", "Gewünschte Domain", "İstenen alan adı", "Domaine souhaité", "Dominio deseado"),
  deposit: translated("عربون الحجز الآن، وليس كامل تكلفة المشروع", "Reservation deposit, not the full project cost", "Reserveringsbedrag, niet de volledige projectkosten", "Reservierungsanzahlung, nicht die gesamten Projektkosten", "Rezervasyon ön ödemesi, tam proje maliyeti değil", "Acompte de réservation, pas le coût total du projet", "Depósito de reserva, no el coste total del proyecto"),
  title: translated("اختيار تفاصيل المشروع", "Choose project details", "Projectdetails kiezen", "Projektdetails auswählen", "Proje ayrıntılarını seçin", "Choisir les détails du projet", "Elegir detalles del proyecto"),
  intro: translated("اختر ما تحتاجه خطوة بخطوة. راجع التكلفة واحفظ طلبك، ثم ادفع عندما تكون جاهزًا.", "Configure your scope, review the estimate, and save your request. Pay when you are ready.", "Kies de omvang, bekijk de raming en sla uw aanvraag op. Betaal wanneer u klaar bent.", "Umfang wählen, Kostenschätzung prüfen und Anfrage speichern. Bezahlen Sie später.", "Kapsamı seçin, tahmini inceleyin ve talebi kaydedin. Hazır olduğunuzda ödeyin.", "Configurez le périmètre, vérifiez l'estimation et enregistrez. Payez lorsque vous êtes prêt.", "Configure el alcance, revise la estimación y guarde. Pague cuando esté listo."),
  kind: translated("نوع المشروع", "Project type", "Projecttype", "Projekttyp", "Proje türü", "Type de projet", "Tipo de proyecto"),
  extras: translated("إضافات وخدمات مستمرة", "Add-ons and ongoing services", "Extra's en doorlopende diensten", "Extras und laufende Leistungen", "Ek ve sürekli hizmetler", "Options et services continus", "Extras y servicios continuos"),
  modules: translated("الميزات والوحدات", "Features and modules", "Functies en modules", "Funktionen und Module", "Özellikler ve modüller", "Fonctionnalités et modules", "Funciones y módulos"),
  delivery: translated("الأداء ووقت التسليم", "Performance and delivery", "Prestaties en oplevering", "Leistung und Lieferung", "Performans ve teslimat", "Performance et livraison", "Rendimiento y entrega"),
  contact: translated("بيانات المشروع", "Project information", "Projectgegevens", "Projektangaben", "Proje bilgileri", "Informations du projet", "Información del proyecto"),
  review: translated("مراجعة المشروع والدفع", "Review and payment", "Controle en betaling", "Prüfung und Zahlung", "İnceleme ve ödeme", "Vérification et paiement", "Revisión y pago"),
  providers: translated("طرق تسجيل الدخول", "Sign-in providers", "Aanmeldmethoden", "Anmeldemethoden", "Giriş yöntemleri", "Méthodes de connexion", "Métodos de inicio de sesión"),
  providerHint: translated("اختر الطرق المطلوبة لمشروعك. السعر تكلفة الربط مرة واحدة؛ رسوم المزود إن وجدت منفصلة.", "Select providers for your project. Prices are one-time integration costs; provider fees are separate.", "Kies providers voor uw project. Eenmalige integratiekosten; eventuele providerkosten zijn apart.", "Einmalige Integrationskosten; mögliche Anbietergebühren sind separat.", "Tek seferlik entegrasyon bedeli; sağlayıcı ücretleri ayrıdır.", "Coût d'intégration unique ; frais éventuels du fournisseur séparés.", "Coste de integración único; las tarifas del proveedor son aparte."),
  languages: translated("لغات المشروع", "Project languages", "Projecttalen", "Projektsprachen", "Proje dilleri", "Langues du projet", "Idiomas del proyecto"),
  languageHint: translated("لغة أساسية مشمولة، وكل لغة إضافية تُحسب مرة واحدة. كتابة وترجمة المحتوى ليست مشمولة.", "One language included; each additional language is charged once. Content writing and translation are excluded.", "Eén taal inbegrepen; elke extra taal kost eenmalig. Tekst en vertaling zijn niet inbegrepen.", "Eine Sprache inklusive; weitere Sprachen einmalig. Texte und Übersetzung nicht enthalten.", "Bir dil dahildir; ek diller tek seferlik ücretlidir. İçerik ve çeviri hariçtir.", "Une langue incluse ; supplément unique par langue. Rédaction et traduction exclues.", "Un idioma incluido; pago único por idioma adicional. Redacción y traducción no incluidas."),
  days: translated("المدة المطلوبة بالأيام", "Requested duration in days", "Gewenste duur in dagen", "Gewünschte Dauer in Tagen", "İstenen süre (gün)", "Durée souhaitée en jours", "Duración solicitada en días"),
  minimum: translated("الحد الأدنى لهذا النطاق", "Minimum for this scope", "Minimum voor deze omvang", "Minimum für diesen Umfang", "Bu kapsam için minimum", "Minimum pour ce périmètre", "Mínimo para este alcance"),
  timing: translated("مدة تقريبية تبدأ بعد تأكيد الدفع واعتماد النطاق وتسليم المحتوى. اختيارك يخضع لتأكيد الفريق.", "Estimated duration starts after payment, scope approval and content delivery. Your requested schedule needs team confirmation.", "Geschatte duur vanaf betaling, scopegoedkeuring en ontvangst van inhoud. Planning vereist teambevestiging.", "Schätzung ab Zahlung, Umfangsfreigabe und Inhalteingang. Terminbestätigung durch das Team erforderlich.", "Tahmin ödeme, kapsam onayı ve içerik tesliminden sonra başlar. Takvim ekip tarafından onaylanır.", "Estimation après paiement, validation du périmètre et réception du contenu. Calendrier à confirmer par l'équipe.", "Estimación tras pago, aprobación y entrega de contenido. El equipo debe confirmar el calendario."),
  oneTime: translated("مرة واحدة", "One time", "Eenmalig", "Einmalig", "Tek sefer", "Une fois", "Pago único"),
  month: translated("شهريًا", "Monthly", "Maandelijks", "Monatlich", "Aylık", "Mensuel", "Mensual"),
  year: translated("سنويًا", "Yearly", "Jaarlijks", "Jährlich", "Yıllık", "Annuel", "Anual"),
  free: translated("مشمولة", "Included", "Inbegrepen", "Inklusive", "Dahil", "Inclus", "Incluido"),
  none: translated("لم تُضف خيارات", "No options selected", "Geen opties gekozen", "Keine Optionen gewählt", "Seçenek seçilmedi", "Aucune option sélectionnée", "Sin opciones seleccionadas"),
  saveLater: translated("حفظ الطلب والدفع لاحقًا", "Save and pay later", "Opslaan en later betalen", "Speichern und später bezahlen", "Kaydet ve sonra öde", "Enregistrer et payer plus tard", "Guardar y pagar después"),
  payNow: translated("حفظ الطلب ثم الانتقال للدفع", "Save and continue to payment", "Opslaan en doorgaan naar betaling", "Speichern und zur Zahlung", "Kaydet ve ödemeye geç", "Enregistrer et passer au paiement", "Guardar y continuar al pago"),
  saveEdit: translated("حفظ تعديلات المشروع", "Save project changes", "Projectwijzigingen opslaan", "Projektänderungen speichern", "Proje değişikliklerini kaydet", "Enregistrer les modifications", "Guardar cambios del proyecto"),
  paymentNote: translated("الدفع الآن اختياري. لن يبدأ التنفيذ قبل تأكيد الدفع واعتماد الطلب. PayPal والبطاقات المتاحة لدى PayPal في صفحة الدفع الآمنة.", "Payment is optional now. Work starts after confirmed payment and scope approval. PayPal and eligible cards are available on the secure payment page.", "Nu betalen is optioneel. Werk start na bevestigde betaling en scopegoedkeuring. PayPal en beschikbare kaarten op de veilige betaalpagina.", "Zahlung jetzt optional. Start nach bestätigter Zahlung und Freigabe. PayPal und verfügbare Karten auf der sicheren Zahlungsseite.", "Şimdi ödeme isteğe bağlıdır. Çalışma onaylı ödeme ve kapsamdan sonra başlar. Güvenli sayfada PayPal ve uygun kartlar bulunur.", "Paiement immédiat facultatif. Travail après paiement confirmé et validation. PayPal et cartes éligibles sur la page sécurisée.", "Pagar ahora es opcional. Trabajo tras pago confirmado y aprobación. PayPal y tarjetas elegibles en la página segura."),
  terms: translated("أسعار تقديرية باليورو قبل ضريبة القيمة المضافة. رسوم بوابات الدفع، المتاجر، تراخيص البرامج واستهلاك السحابة منفصلة. الاشتراكات المختارة لا تُفعّل تلقائيًا ولا يتم تجديدها دون موافقتك.", "EUR estimates exclude VAT. Payment gateway, app store, software licence and cloud usage fees are separate. Selected recurring services are not activated or renewed automatically without your consent.", "EUR-ramingen exclusief btw. Gateway-, appstore-, licentie- en cloudkosten zijn apart. Doorlopende diensten worden niet automatisch geactiveerd of verlengd zonder toestemming.", "EUR-Schätzungen ohne MwSt. Gateway-, App-Store-, Lizenz- und Cloudkosten separat. Keine automatische Aktivierung oder Verlängerung ohne Zustimmung.", "EUR tahminleri KDV hariçtir. Ödeme, mağaza, lisans ve bulut kullanım ücretleri ayrıdır. Onayınız olmadan abonelik başlatılmaz veya yenilenmez.", "Estimations EUR hors TVA. Frais de paiement, boutiques, licences et cloud séparés. Aucune activation ou reconduction automatique sans accord.", "Estimaciones EUR sin IVA. Tarifas de pagos, tiendas, licencias y nube aparte. Sin activación ni renovación automática sin consentimiento."),
  blocked: translated("لا يمكن تعديل الخيارات أثناء الدفع أو بعد تأكيده، أو بعد بدء التصميم. تواصل معنا لتعديل نطاق مشروع مدفوع.", "Options cannot be changed during payment, after payment confirmation or after design starts. Contact us for scope changes on a paid project.", "Opties zijn geblokkeerd tijdens/na betaling of na de start van ontwerp. Neem contact op voor wijzigingen aan betaalde projecten.", "Optionen während/nach Zahlung oder nach Designstart gesperrt. Kontaktieren Sie uns für bezahlte Projekte.", "Ödeme sırasında/sonrasında veya tasarım başladığında seçenekler değiştirilemez. Ödenmiş proje değişiklikleri için iletişime geçin.", "Options bloquées pendant/après paiement ou après le début du design. Contactez-nous pour modifier un projet payé.", "Opciones bloqueadas durante/después del pago o al iniciar diseño. Contáctenos para modificar un proyecto pagado."),
  error: translated("تعذّر الحفظ. تحقق من الخيارات وحاول مجددًا؛ لا يمكن تعديل طلب مقفل أو طلب له عملية دفع نشطة.", "Could not save. Check your options and retry; locked requests or active payments cannot be changed.", "Opslaan mislukt. Controleer opties; vergrendelde aanvragen of actieve betalingen kunnen niet worden gewijzigd.", "Speichern fehlgeschlagen. Optionen prüfen; gesperrte Anfragen oder aktive Zahlungen nicht änderbar.", "Kaydedilemedi. Seçenekleri kontrol edin; kilitli talepler veya etkin ödemeler değiştirilemez.", "Enregistrement impossible. Vérifiez les options ; demandes verrouillées ou paiements actifs non modifiables.", "No se pudo guardar. Revise opciones; solicitudes bloqueadas o pagos activos no se pueden modificar."),
  saved: translated("تم حفظ تفاصيل المشروع في حسابك.", "Project details saved to your account.", "Projectdetails opgeslagen in uw account.", "Projektdetails im Konto gespeichert.", "Proje ayrıntıları hesabınıza kaydedildi.", "Détails enregistrés dans votre compte.", "Detalles guardados en su cuenta."),
};
