import { withExtraLocales } from "./extra-locales";
import type { Locale } from "./config";
const copy = withExtraLocales({
  ar: { company: "موقع شركة", store: "متجر إلكتروني", apps: "تطبيق", systems: "نظام مخصص", intro: "اختر المسار المناسب، ثم استكشف الأنواع والقوالب وحدد تفاصيل مشروعك.", audience: "للشركات والمشاريع الناشئة: مواقع ومتاجر وتطبيقات من التصميم حتى الإطلاق. اختر الخدمة وحدد احتياجاتك لتحصل على عرض واضح يعتمد قبل التنفيذ." },
  en: { company: "Company website", store: "Online store", apps: "Application", systems: "Custom system", intro: "Choose a path, explore its services and templates, then define your project.", audience: "For businesses and startups: websites, stores and apps from design to launch. Choose a service and define your needs for a clear quote approved before implementation." },
  nl: { company: "Bedrijfswebsite", store: "Webwinkel", apps: "Applicatie", systems: "Maatwerksysteem", intro: "Kies een richting, bekijk de diensten en sjablonen en bepaal uw project.", audience: "Voor bedrijven en startups: websites, winkels en apps van ontwerp tot lancering. Kies een dienst en beschrijf uw wensen voor een duidelijke offerte vóór uitvoering." },
  de: { company: "Unternehmenswebsite", store: "Onlineshop", apps: "Anwendung", systems: "Individuelles System", intro: "Wählen Sie einen Bereich, prüfen Sie Leistungen und Vorlagen und definieren Sie Ihr Projekt.", audience: "Für Unternehmen und Startups: Websites, Shops und Apps vom Design bis zum Start. Wählen Sie eine Leistung und beschreiben Sie Ihren Bedarf für ein Angebot vor der Umsetzung." },
  tr: { company: "Şirket sitesi", store: "Online mağaza", apps: "Uygulama", systems: "Özel sistem", intro: "Bir alan seçin, hizmetleri ve şablonları inceleyin, ardından projenizi tanımlayın.", audience: "Şirketler ve girişimler için tasarımdan yayına web siteleri, mağazalar ve uygulamalar. Hizmeti seçip ihtiyaçları belirleyin; uygulama öncesinde net teklif onaylanır." },
  fr: { company: "Site d’entreprise", store: "Boutique en ligne", apps: "Application", systems: "Système sur mesure", intro: "Choisissez un domaine, explorez ses services et modèles puis définissez votre projet.", audience: "Pour entreprises et startups : sites, boutiques et applications du design au lancement. Choisissez un service et vos besoins pour un devis clair validé avant réalisation." },
  es: { company: "Web de empresa", store: "Tienda online", apps: "Aplicación", systems: "Sistema a medida", intro: "Elija un área, explore sus servicios y plantillas y defina su proyecto.", audience: "Para empresas y startups: webs, tiendas y aplicaciones desde el diseño al lanzamiento. Elija el servicio y sus necesidades para aprobar una propuesta clara antes de desarrollar." },
} as const);
export function solutionCopy(locale: Locale) { return copy[locale]; }
