import type { Locale } from "./config";
const rows: Record<Locale, string[]> = {
 ar: ["أدوات مجانية لأعمالك وموقعك", "ابحث عن أداة", "الكل", "المواقع", "SEO", "الحماية", "الذكاء الاصطناعي", "الأعمال", "التسويق", "افتح الأداة", "مجاني", "يتطلب حسابًا", "البيانات", "إنشاء", "تحميل", "جاري المعالجة…", "تعذر تنفيذ الطلب. راجع البيانات وحاول مرة أخرى.", "هذه الخدمة غير مفعلة حاليًا.", "حفظ التقارير", "الاستخدام المتبقي", "لا توجد نتائج", "العنوان", "التفاصيل", "السعر", "الحالة", "إرسال", "لوحتي", "عودة", "معاينة الموقع", "نسخ", "تم النسخ", "اللغات", "التقرير"],
 en: ["Free business and website tools", "Search tools", "All", "Website", "SEO", "Security", "AI", "Business", "Marketing", "Open tool", "Free", "Account required", "Data", "Generate", "Download", "Processing…", "Unable to complete this request. Check your input and retry.", "This service is not currently enabled.", "Saved reports", "Usage remaining", "No results", "Title", "Details", "Price", "Status", "Submit", "My dashboard", "Back", "Website preview", "Copy", "Copied", "Languages", "Report"],
 nl: ["Gratis zakelijke en websitetools", "Zoek tools", "Alle", "Website", "SEO", "Beveiliging", "AI", "Zakelijk", "Marketing", "Open tool", "Gratis", "Account vereist", "Gegevens", "Genereren", "Downloaden", "Bezig…", "Controleer uw invoer en probeer opnieuw.", "Deze dienst is nog niet ingeschakeld.", "Opgeslagen rapporten", "Resterend gebruik", "Geen resultaten", "Titel", "Details", "Prijs", "Status", "Versturen", "Mijn dashboard", "Terug", "Websitevoorbeeld", "Kopiëren", "Gekopieerd", "Talen", "Rapport"],
 de: ["Kostenlose Geschäfts- und Webtools", "Tools suchen", "Alle", "Website", "SEO", "Sicherheit", "KI", "Geschäft", "Marketing", "Tool öffnen", "Kostenlos", "Konto erforderlich", "Daten", "Erstellen", "Herunterladen", "Verarbeitung…", "Eingabe prüfen und erneut versuchen.", "Dieser Dienst ist noch nicht aktiviert.", "Gespeicherte Berichte", "Verbleibende Nutzung", "Keine Ergebnisse", "Titel", "Details", "Preis", "Status", "Senden", "Mein Dashboard", "Zurück", "Websitevorschau", "Kopieren", "Kopiert", "Sprachen", "Bericht"],
 tr: ["Ücretsiz iş ve web araçları", "Araç ara", "Tümü", "Web sitesi", "SEO", "Güvenlik", "Yapay zekâ", "İş", "Pazarlama", "Aracı aç", "Ücretsiz", "Hesap gerekli", "Veriler", "Oluştur", "İndir", "İşleniyor…", "Girdiyi kontrol edip tekrar deneyin.", "Bu hizmet henüz etkin değil.", "Kayıtlı raporlar", "Kalan kullanım", "Sonuç yok", "Başlık", "Ayrıntılar", "Fiyat", "Durum", "Gönder", "Panelim", "Geri", "Site önizlemesi", "Kopyala", "Kopyalandı", "Diller", "Rapor"],
 fr: ["Outils gratuits pour entreprises et sites", "Rechercher", "Tous", "Site web", "SEO", "Sécurité", "IA", "Entreprise", "Marketing", "Ouvrir", "Gratuit", "Compte requis", "Données", "Générer", "Télécharger", "Traitement…", "Vérifiez les données et réessayez.", "Ce service n’est pas encore activé.", "Rapports enregistrés", "Utilisation restante", "Aucun résultat", "Titre", "Détails", "Prix", "Statut", "Envoyer", "Mon tableau de bord", "Retour", "Aperçu du site", "Copier", "Copié", "Langues", "Rapport"],
 es: ["Herramientas gratuitas para negocios y sitios", "Buscar", "Todas", "Sitio web", "SEO", "Seguridad", "IA", "Negocios", "Marketing", "Abrir", "Gratis", "Requiere cuenta", "Datos", "Generar", "Descargar", "Procesando…", "Revisa los datos e inténtalo de nuevo.", "Este servicio aún no está activado.", "Informes guardados", "Uso restante", "Sin resultados", "Título", "Detalles", "Precio", "Estado", "Enviar", "Mi panel", "Volver", "Vista del sitio", "Copiar", "Copiado", "Idiomas", "Informe"],
 it: ["Strumenti gratuiti per aziende e siti", "Cerca", "Tutti", "Sito", "SEO", "Sicurezza", "IA", "Azienda", "Marketing", "Apri", "Gratis", "Account richiesto", "Dati", "Genera", "Scarica", "Elaborazione…", "Controlla i dati e riprova.", "Servizio non ancora attivo.", "Rapporti salvati", "Utilizzo residuo", "Nessun risultato", "Titolo", "Dettagli", "Prezzo", "Stato", "Invia", "La mia dashboard", "Indietro", "Anteprima sito", "Copia", "Copiato", "Lingue", "Rapporto"],
 pt: ["Ferramentas gratuitas para empresas e sites", "Pesquisar", "Todas", "Site", "SEO", "Segurança", "IA", "Negócios", "Marketing", "Abrir", "Grátis", "Conta necessária", "Dados", "Gerar", "Transferir", "Processando…", "Verifique os dados e tente novamente.", "Serviço ainda não ativo.", "Relatórios guardados", "Uso restante", "Sem resultados", "Título", "Detalhes", "Preço", "Estado", "Enviar", "Meu painel", "Voltar", "Prévia do site", "Copiar", "Copiado", "Idiomas", "Relatório"],
 pl: ["Bezpłatne narzędzia dla firm i stron", "Szukaj", "Wszystkie", "Strona", "SEO", "Bezpieczeństwo", "AI", "Firma", "Marketing", "Otwórz", "Bezpłatne", "Wymaga konta", "Dane", "Generuj", "Pobierz", "Przetwarzanie…", "Sprawdź dane i spróbuj ponownie.", "Usługa nie jest jeszcze aktywna.", "Zapisane raporty", "Pozostałe użycie", "Brak wyników", "Tytuł", "Szczegóły", "Cena", "Status", "Wyślij", "Mój panel", "Wstecz", "Podgląd strony", "Kopiuj", "Skopiowano", "Języki", "Raport"],
 uk: ["Безкоштовні інструменти для бізнесу й сайтів", "Пошук", "Усі", "Сайт", "SEO", "Безпека", "ШІ", "Бізнес", "Маркетинг", "Відкрити", "Безкоштовно", "Потрібен обліковий запис", "Дані", "Створити", "Завантажити", "Обробка…", "Перевірте дані та повторіть.", "Послугу ще не активовано.", "Збережені звіти", "Залишок використання", "Немає результатів", "Назва", "Деталі", "Ціна", "Стан", "Надіслати", "Моя панель", "Назад", "Перегляд сайту", "Копіювати", "Скопійовано", "Мови", "Звіт"],
 ru: ["Бесплатные инструменты для бизнеса и сайтов", "Поиск", "Все", "Сайт", "SEO", "Безопасность", "ИИ", "Бизнес", "Маркетинг", "Открыть", "Бесплатно", "Нужен аккаунт", "Данные", "Создать", "Скачать", "Обработка…", "Проверьте данные и повторите.", "Сервис ещё не активирован.", "Сохранённые отчёты", "Остаток использования", "Нет результатов", "Название", "Детали", "Цена", "Статус", "Отправить", "Моя панель", "Назад", "Просмотр сайта", "Копировать", "Скопировано", "Языки", "Отчёт"],
 zh: ["免费企业与网站工具", "搜索工具", "全部", "网站", "SEO", "安全", "AI", "企业", "营销", "打开", "免费", "需要账号", "数据", "生成", "下载", "处理中…", "请检查数据后重试。", "服务尚未启用。", "已保存报告", "剩余用量", "无结果", "标题", "详情", "价格", "状态", "提交", "我的面板", "返回", "网站预览", "复制", "已复制", "语言", "报告"],
 ja: ["ビジネスとサイト向け無料ツール", "検索", "すべて", "サイト", "SEO", "安全", "AI", "ビジネス", "マーケティング", "開く", "無料", "アカウントが必要", "データ", "生成", "ダウンロード", "処理中…", "入力を確認して再試行してください。", "サービスはまだ有効ではありません。", "保存済みレポート", "残り利用数", "結果なし", "タイトル", "詳細", "価格", "状態", "送信", "マイページ", "戻る", "サイトプレビュー", "コピー", "コピー済み", "言語", "レポート"],
 ko: ["비즈니스 및 웹사이트 무료 도구", "검색", "전체", "사이트", "SEO", "보안", "AI", "비즈니스", "마케팅", "열기", "무료", "계정 필요", "데이터", "생성", "다운로드", "처리 중…", "데이터를 확인하고 다시 시도하세요.", "아직 활성화되지 않은 서비스입니다.", "저장된 보고서", "남은 사용량", "결과 없음", "제목", "상세", "가격", "상태", "제출", "내 대시보드", "뒤로", "사이트 미리보기", "복사", "복사됨", "언어", "보고서"],
};
export function toolsUi(locale: Locale) {
 const [heading,search,all,website,seo,security,ai,business,marketing,open,free,account,data,generate,download,processing,error,unavailable,saved,remaining,empty,title,details,price,status,submit,dashboard,back,preview,copy,copied,languages,report] = rows[locale];
 return {heading,search,all,categories:{website,seo,security,ai,business,marketing},open,free,account,data,generate,download,processing,error,unavailable,saved,remaining,empty,title,details,price,status,submit,dashboard,back,preview,copy,copied,languages,report};
}
