import type {Locale} from "./config";
const rows:Record<Locale,string[]>={
 ar:["سكربتات التحليلات","سكربتات التسويق","كوكيز استجابة HTTP","مؤشرات موافقة داخل HTML","تعليمات Robots","وسوم Open Graph","بيانات منظمة","هذه ملاحظات تقنية من الصفحة المقروءة؛ لا تشمل تتبع المتصفح بعد التشغيل ولا تعني التوافق القانوني مع GDPR.","النطاق واللغات المختارة تقديرية؛ تعتمد الإدارة السعر النهائي."],
 en:["Analytics scripts","Marketing scripts","HTTP response cookies","Consent markers in HTML","Robots directives","Open Graph tags","Structured data","Technical observations from the fetched page; browser behaviour after execution is not inspected and legal GDPR compliance is not determined.","Scope and language pricing are estimates; the final price is approved by management."],
 nl:["Analysescripts","Marketingscripts","HTTP-responscookies","Toestemmingsmarkers in HTML","Robots-instructies","Open Graph-tags","Gestructureerde gegevens","Technische observaties van de opgehaalde pagina; browsergedrag na uitvoering en juridische AVG-naleving worden niet gecontroleerd.","Omvang en taalprijzen zijn schattingen; de definitieve prijs wordt goedgekeurd."],
 de:["Analyseskripte","Marketingskripte","HTTP-Antwortcookies","Einwilligungsmarker im HTML","Robots-Anweisungen","Open-Graph-Tags","Strukturierte Daten","Technische Beobachtungen der abgerufenen Seite; Browserausführung und rechtliche DSGVO-Konformität werden nicht geprüft.","Umfang und Sprachpreise sind Schätzungen; der Endpreis wird freigegeben."],
 tr:["Analiz betikleri","Pazarlama betikleri","HTTP yanıt çerezleri","HTML onay işaretleri","Robots yönergeleri","Open Graph etiketleri","Yapılandırılmış veri","Alınan sayfadaki teknik gözlemler; çalıştırma sonrası tarayıcı davranışı ve hukuki GDPR uyumu incelenmez.","Kapsam ve dil fiyatları tahminidir; son fiyat yönetimce onaylanır."],
 fr:["Scripts analytiques","Scripts marketing","Cookies de réponse HTTP","Marqueurs de consentement HTML","Directives Robots","Balises Open Graph","Données structurées","Observations techniques de la page récupérée; comportement du navigateur après exécution et conformité juridique RGPD non évalués.","Périmètre et langues estimés; prix final validé par la direction."],
 es:["Scripts analíticos","Scripts de marketing","Cookies de respuesta HTTP","Marcadores de consentimiento HTML","Directivas Robots","Etiquetas Open Graph","Datos estructurados","Observaciones técnicas de la página; no evalúa ejecución del navegador ni cumplimiento legal del RGPD.","Alcance e idiomas estimados; el precio final requiere aprobación."],
 it:["Script analitici","Script marketing","Cookie risposta HTTP","Indicatori consenso HTML","Direttive Robots","Tag Open Graph","Dati strutturati","Osservazioni tecniche della pagina; non valuta esecuzione del browser o conformità legale GDPR.","Ambito e lingue stimati; prezzo finale da approvare."],
 pt:["Scripts analíticos","Scripts de marketing","Cookies de resposta HTTP","Marcadores de consentimento HTML","Diretivas Robots","Etiquetas Open Graph","Dados estruturados","Observações técnicas da página; execução do navegador e conformidade jurídica RGPD não avaliadas.","Âmbito e idiomas estimados; preço final sujeito a aprovação."],
 pl:["Skrypty analityczne","Skrypty marketingowe","Cookies odpowiedzi HTTP","Znaczniki zgody w HTML","Dyrektywy Robots","Tagi Open Graph","Dane strukturalne","Techniczne obserwacje strony; nie obejmują działania przeglądarki ani zgodności prawnej z RODO.","Zakres i języki są szacunkowe; cena końcowa wymaga zatwierdzenia."],
 uk:["Аналітичні скрипти","Маркетингові скрипти","Cookies відповіді HTTP","Ознаки згоди в HTML","Директиви Robots","Теги Open Graph","Структуровані дані","Технічні спостереження сторінки; виконання у браузері та правова відповідність GDPR не перевіряються.","Обсяг і мови оцінені приблизно; остаточну ціну затверджує адміністрація."],
 ru:["Аналитические скрипты","Маркетинговые скрипты","Cookies ответа HTTP","Признаки согласия в HTML","Директивы Robots","Теги Open Graph","Структурированные данные","Технические наблюдения страницы; работа браузера и правовое соответствие GDPR не проверяются.","Объём и языки оценены приблизительно; итоговую цену утверждает администрация."],
 zh:["分析脚本","营销脚本","HTTP响应Cookie","HTML同意标记","Robots指令","Open Graph标签","结构化数据","获取页面的技术观察，不检查浏览器运行行为，也不判定GDPR法律合规性。","范围与语言价格为估算，最终价格由管理人员批准。"],
 ja:["分析スクリプト","広告スクリプト","HTTP応答Cookie","HTML内の同意マーカー","Robots指示","Open Graphタグ","構造化データ","取得ページの技術的観察です。ブラウザ実行やGDPRの法的適合性は評価しません。","範囲と言語料金は概算です。最終価格は管理者が承認します。"],
 ko:["분석 스크립트","마케팅 스크립트","HTTP 응답 쿠키","HTML 동의 표시","Robots 지침","Open Graph 태그","구조화 데이터","가져온 페이지의 기술적 관찰입니다. 브라우저 실행 및 GDPR 법적 준수는 평가하지 않습니다.","범위와 언어 가격은 추정치이며 최종 가격은 관리자가 승인합니다."],
};
export function toolObservations(locale:Locale){const [analyticsScripts,marketingScripts,responseCookies,consentMarkup,robots,openGraph,structuredData,privacyNote,estimateNote]=rows[locale];return {labels:{analyticsScripts,marketingScripts,responseCookies,consentMarkup,robots,openGraph,structuredData},privacyNote,estimateNote};}
