import Image from "next/image";
import { notFound } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import { CallToAction } from "@/components/public/process";
import { isLocale } from "@/lib/i18n";

const copy = {
  ar: { eyebrow: "من نحن", title: "فريق منتج واحد، ومسؤولية واضحة.", intro: "بلو ساس استوديو رقمي في هولندا يجمع الاستراتيجية وتجربة المستخدم والتصميم والتطوير. نشاركك القرار من تعريف المشكلة حتى الإطلاق والتحسين.", values: [["نفهم قبل أن نصمم", "نبدأ بالأهداف والمستخدمين والمحتوى، لا بالشكل وحده."], ["نبني للنمو", "أساس تقني سريع وقابل للتطوير بدل حلول مؤقتة."], ["تواصل بلا غموض", "نطاق وميزانية ومراحل واضحة، وتحديثات مرئية داخل حسابك."]], caption: "جلسة عمل تجمع المنتج والتصميم والتطوير حول قرار واحد.", promise: "ما الذي تحصل عليه؟", points: ["فريق واحد بدل التنسيق بين عدة جهات", "نماذج حقيقية قبل التطوير", "ملكية واضحة ودعم بعد الإطلاق"] },
  en: { eyebrow: "About us", title: "One product team. Clear accountability.", intro: "Blue Sass is a Netherlands-based digital studio combining strategy, UX, design and engineering. We work with you from defining the problem through launch and improvement.", values: [["Understand before design", "We start with goals, users and content—not visuals alone."], ["Built to grow", "A fast, scalable technical foundation instead of temporary fixes."], ["Communication without fog", "Clear scope, budget and stages with visible updates in your account."]], caption: "A working session bringing product, design and engineering around one decision.", promise: "What you receive", points: ["One team instead of coordinating multiple suppliers", "Real prototypes before development", "Clear ownership and post-launch support"] },
  nl: { eyebrow: "Over ons", title: "Eén productteam. Duidelijke verantwoordelijkheid.", intro: "Blue Sass is een Nederlandse digitale studio voor strategie, UX, ontwerp en ontwikkeling. Van probleemdefinitie tot livegang en verbetering werken we met u samen.", values: [["Begrijpen vóór ontwerpen", "We beginnen met doelen, gebruikers en content."], ["Gebouwd om te groeien", "Een snelle, schaalbare technische basis."], ["Communicatie zonder ruis", "Heldere scope, budget en fasen met zichtbare updates."]], caption: "Product, ontwerp en techniek samen rond één besluit.", promise: "Wat u ontvangt", points: ["Eén team in plaats van meerdere leveranciers", "Echte prototypes vóór ontwikkeling", "Duidelijk eigenaarschap en nazorg"] },
  de: { eyebrow: "Über uns", title: "Ein Produktteam. Klare Verantwortung.", intro: "Blue Sass ist ein niederländisches Digitalstudio für Strategie, UX, Design und Entwicklung. Wir begleiten Sie von der Problemdefinition bis zu Launch und Optimierung.", values: [["Verstehen vor Gestalten", "Wir starten mit Zielen, Nutzern und Inhalten."], ["Für Wachstum gebaut", "Eine schnelle und skalierbare technische Basis."], ["Klare Kommunikation", "Transparenter Umfang, Budget und sichtbare Updates."]], caption: "Produkt, Design und Technik treffen gemeinsam Entscheidungen.", promise: "Was Sie erhalten", points: ["Ein Team statt mehrerer Anbieter", "Echte Prototypen vor der Entwicklung", "Klare Rechte und Support nach dem Launch"] },
  tr: { eyebrow: "Hakkımızda", title: "Tek ürün ekibi. Net sorumluluk.", intro: "Blue Sass; strateji, UX, tasarım ve mühendisliği birleştiren Hollanda merkezli dijital stüdyodur. Sorundan lansman ve iyileştirmeye kadar birlikte çalışırız.", values: [["Tasarımdan önce anlarız", "Hedefler, kullanıcılar ve içerikle başlarız."], ["Büyümek için inşa", "Hızlı ve ölçeklenebilir teknik temel."], ["Açık iletişim", "Net kapsam, bütçe, aşamalar ve görünür güncellemeler."]], caption: "Ürün, tasarım ve geliştirme tek karar etrafında.", promise: "Neler alırsınız", points: ["Birden fazla tedarikçi yerine tek ekip", "Geliştirmeden önce gerçek prototipler", "Net sahiplik ve lansman sonrası destek"] },
  fr: { eyebrow: "À propos", title: "Une équipe produit. Une responsabilité claire.", intro: "Blue Sass est un studio numérique néerlandais réunissant stratégie, UX, design et développement. Nous avançons avec vous du problème au lancement puis à l’amélioration.", values: [["Comprendre avant de concevoir", "Nous partons des objectifs, utilisateurs et contenus."], ["Conçu pour grandir", "Une base technique rapide et évolutive."], ["Communication limpide", "Périmètre, budget, étapes et suivi visibles."]], caption: "Produit, design et technique réunis autour d’une décision.", promise: "Ce que vous obtenez", points: ["Une équipe plutôt que plusieurs prestataires", "De vrais prototypes avant le développement", "Des droits clairs et un support après lancement"] },
  es: { eyebrow: "Nosotros", title: "Un equipo de producto. Responsabilidad clara.", intro: "Blue Sass es un estudio digital neerlandés que une estrategia, UX, diseño y desarrollo. Trabajamos con usted desde el problema hasta el lanzamiento y la mejora.", values: [["Entender antes de diseñar", "Empezamos por objetivos, usuarios y contenido."], ["Preparado para crecer", "Una base técnica rápida y escalable."], ["Comunicación clara", "Alcance, presupuesto, fases y avances visibles."]], caption: "Producto, diseño y desarrollo alrededor de una decisión.", promise: "Qué recibe", points: ["Un equipo en lugar de varios proveedores", "Prototipos reales antes del desarrollo", "Propiedad clara y soporte posterior"] },
} as const;

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const c = copy[locale];
  return <>
    <section className="bg-base"><div className="container-x grid items-center gap-12 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-24"><div><span className="text-sm font-bold text-neon-blue">✦ {c.eyebrow}</span><h1 className="mt-5 text-5xl font-bold leading-tight text-black sm:text-7xl">{c.title}</h1><p className="mt-6 max-w-xl text-lg leading-9 text-ink-low">{c.intro}</p></div><figure className="overflow-hidden rounded-[2rem] border-2 border-black bg-black"><Image src="/media/about-studio-v2.png" alt={c.caption} width={1536} height={1024} className="aspect-[4/3] w-full object-cover" priority/><figcaption className="px-5 py-4 text-sm text-white/65">{c.caption}</figcaption></figure></div></section>
    <section className="bg-white py-20"><div className="container-x"><div className="grid gap-4 md:grid-cols-3">{c.values.map(([title,body], index)=><article key={title} className="rounded-2xl border border-black/15 bg-base p-6"><span className="font-mono text-xs text-ink-low">0{index+1}</span><h2 className="mt-8 text-2xl font-bold">{title}</h2><p className="mt-3 leading-7 text-ink-low">{body}</p></article>)}</div><div className="mt-14 grid gap-6 rounded-3xl bg-black p-7 text-white md:grid-cols-[.7fr_1fr] md:p-10"><h2 className="text-3xl font-bold text-white">{c.promise}</h2><ul className="space-y-4">{c.points.map(point=><li key={point} className="flex gap-3 text-white/75"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-neon-cyan"/>{point}</li>)}</ul></div></div></section>
    <CallToAction />
  </>;
}
